# -*- coding: utf-8 -*-
"""矛盾测试集 v59（16 生活常识·常识迁移 c10）"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")
ITEMS = [
    {"q": "为什么要刷牙？", "domain": "刷牙护牙", "stage": "正题",
     "need": "清除细菌防蛀牙", "conflict": "刷牙护牙 vs 细菌蛀牙"},
    {"q": "怎么刷牙才正确？", "domain": "刷牙护牙", "stage": "合题",
     "need": "巴氏刷牙法", "conflict": "刷牙护牙 vs 细菌蛀牙"},
    {"q": "为什么要早睡早起？", "domain": "早睡早起", "stage": "正题",
     "need": "睡眠充足身体好", "conflict": "早睡早起 vs 熬夜"},
    {"q": "熬夜有什么坏处？", "domain": "早睡早起", "stage": "反题",
     "need": "伤免疫记忆", "conflict": "早睡早起 vs 熬夜"},
    {"q": "为什么煮饭饭会熟？", "domain": "煮饭原理", "stage": "正题",
     "need": "淀粉糊化", "conflict": "煮饭原理 vs 加热"},
    {"q": "煮饭水放多少合适？", "domain": "煮饭原理", "stage": "合题",
     "need": "没过一指", "conflict": "煮饭原理 vs 加热"},
    {"q": "被开水烫了怎么办？", "domain": "开水烫", "stage": "合题",
     "need": "冲凉水20分钟", "conflict": "开水烫 vs 安全"},
    {"q": "烫伤能涂牙膏酱油吗？", "domain": "开水烫", "stage": "反题",
     "need": "不能会感染", "conflict": "开水烫 vs 安全"},
    {"q": "为什么晒太阳能补钙？", "domain": "晒太阳补钙", "stage": "正题",
     "need": "合成维生素D", "conflict": "晒太阳补钙 vs 维生素D"},
    {"q": "隔着玻璃晒太阳有用吗？", "domain": "晒太阳补钙", "stage": "反题",
     "need": "没用玻璃挡紫外线", "conflict": "晒太阳补钙 vs 维生素D"},
    {"q": "为什么要开窗通风？", "domain": "开窗通风", "stage": "正题",
     "need": "换新鲜空气", "conflict": "开窗通风 vs 密闭空气"},
    {"q": "多久通一次风？", "domain": "开窗通风", "stage": "合题",
     "need": "每天2-3次", "conflict": "开窗通风 vs 密闭空气"},
    {"q": "为什么要运动前热身？", "domain": "运动热身", "stage": "正题",
     "need": "身体准备防受伤", "conflict": "运动热身 vs 突然运动"},
    {"q": "不热身直接运动会怎样？", "domain": "运动热身", "stage": "反题",
     "need": "拉伤扭伤", "conflict": "运动热身 vs 突然运动"},
    {"q": "为什么要运动后拉伸？", "domain": "运动拉伸", "stage": "正题",
     "need": "放松肌肉缓解酸痛", "conflict": "运动拉伸 vs 肌肉放松"},
    {"q": "热身和拉伸什么区别？", "domain": "运动拉伸", "stage": "反题",
     "need": "动态前静态后", "conflict": "运动拉伸 vs 肌肉放松"},
    {"q": "走路能锻炼身体吗？", "domain": "走路锻炼", "stage": "正题",
     "need": "温和有氧", "conflict": "走路锻炼 vs 剧烈运动"},
    {"q": "每天走多少步？", "domain": "走路锻炼", "stage": "合题",
     "need": "6000-10000步", "conflict": "走路锻炼 vs 剧烈运动"},
    {"q": "为什么要少久坐？", "domain": "久坐活动", "stage": "正题",
     "need": "久坐伤身", "conflict": "久坐活动 vs 活动身体"},
    {"q": "多久起身一次？", "domain": "久坐活动", "stage": "合题",
     "need": "30-60分钟", "conflict": "久坐活动 vs 活动身体"},
    {"q": "为什么用眼久了要休息？", "domain": "用眼休息", "stage": "正题",
     "need": "睫状肌紧张", "conflict": "用眼休息 vs 眼睛疲劳"},
    {"q": "20-20-20法则是什么？", "domain": "用眼休息", "stage": "合题",
     "need": "20分钟看20秒远", "conflict": "用眼休息 vs 眼睛疲劳"},
    {"q": "为什么要吹干头发？", "domain": "吹干头发", "stage": "正题",
     "need": "防受凉", "conflict": "吹干头发 vs 湿发睡觉"},
    {"q": "湿发睡觉有什么坏处？", "domain": "吹干头发", "stage": "反题",
     "need": "细菌头痒受凉", "conflict": "吹干头发 vs 湿发睡觉"},
    {"q": "为什么热水解冻不好？", "domain": "热水解冻", "stage": "反题",
     "need": "外层熟内层冰细菌多", "conflict": "热水解冻 vs 食物安全"},
    {"q": "怎么解冻最安全？", "domain": "热水解冻", "stage": "合题",
     "need": "冷藏解冻", "conflict": "热水解冻 vs 食物安全"},
    {"q": "为什么天冷要保暖？", "domain": "保暖防感冒", "stage": "正题",
     "need": "防受凉保免疫", "conflict": "保暖防感冒 vs 受凉"},
    {"q": "保暖怎么防感冒？", "domain": "保暖防感冒", "stage": "合题",
     "need": "维持体温免疫正常", "conflict": "保暖防感冒 vs 受凉"},
    {"q": "为什么睡前不玩手机？", "domain": "睡前不玩", "stage": "正题",
     "need": "蓝光抑制褪黑素", "conflict": "睡前不玩 vs 屏幕蓝光"},
    {"q": "褪黑素是什么？", "domain": "睡前不玩", "stage": "反题",
     "need": "睡眠激素", "conflict": "睡前不玩 vs 屏幕蓝光"},
    {"q": "为什么渴了要喝水？", "domain": "喝水止渴", "stage": "正题",
     "need": "身体缺水信号", "conflict": "喝水止渴 vs 身体缺水"},
    {"q": "每天喝多少水？", "domain": "喝水止渴", "stage": "合题",
     "need": "1500-1700ml", "conflict": "喝水止渴 vs 身体缺水"},
]
with open(r"D:\Program Files\2_ai\knowledge-base\conflict_testset_v59.json", "w", encoding="utf-8") as f:
    json.dump({"name": "conflict_testset_v59", "conflicts": 16, "items": ITEMS}, f, ensure_ascii=False, indent=1)
print("v59 testset:", len(ITEMS))
