# -*- coding: utf-8 -*-
"""矛盾测试集 v57（15 生活/编程概念·常识迁移 c8）"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")
ITEMS = [
    {"q": "为什么食物放冰箱不容易坏？", "domain": "冰箱保鲜", "stage": "正题",
     "need": "低温抑菌", "conflict": "冰箱保鲜 vs 细菌繁殖"},
    {"q": "冰箱能杀菌吗？", "domain": "冰箱保鲜", "stage": "反题",
     "need": "不杀菌只抑菌", "conflict": "冰箱保鲜 vs 细菌繁殖"},
    {"q": "冷藏和冷冻什么区别？", "domain": "冰箱保鲜", "stage": "合题",
     "need": "4°C短期-18°C长期", "conflict": "冰箱保鲜 vs 细菌繁殖"},
    {"q": "为什么洗澡用热水舒服？", "domain": "热水洗澡", "stage": "正题",
     "need": "血管扩张肌肉放松", "conflict": "热水洗澡 vs 温水洗澡"},
    {"q": "洗澡水多热合适？", "domain": "热水洗澡", "stage": "合题",
     "need": "38-40°C", "conflict": "热水洗澡 vs 温水洗澡"},
    {"q": "为什么夏天穿浅色衣服凉快？", "domain": "浅色衣服", "stage": "正题",
     "need": "反射阳光", "conflict": "浅色衣服 vs 吸热反射"},
    {"q": "防晒穿什么颜色？", "domain": "浅色衣服", "stage": "反题",
     "need": "深色挡紫外线", "conflict": "浅色衣服 vs 吸热反射"},
    {"q": "为什么要远眺护眼？", "domain": "远眺护眼", "stage": "正题",
     "need": "睫状肌放松", "conflict": "远眺护眼 vs 眼睛疲劳"},
    {"q": "远眺能防近视吗？", "domain": "远眺护眼", "stage": "反题",
     "need": "减少眼轴风险", "conflict": "远眺护眼 vs 眼睛疲劳"},
    {"q": "为什么饭后不能马上运动？", "domain": "饭后运动", "stage": "正题",
     "need": "抢走胃部供血", "conflict": "饭后运动 vs 消化供血"},
    {"q": "饭后多久能运动？", "domain": "饭后运动", "stage": "合题",
     "need": "散步半小时剧烈2小时", "conflict": "饭后运动 vs 消化供血"},
    {"q": "散步有什么好处？", "domain": "散步", "stage": "正题",
     "need": "促循环助消化", "conflict": "散步 vs 跑步"},
    {"q": "每天散步好吗？", "domain": "散步", "stage": "反题",
     "need": "30分钟健康", "conflict": "散步 vs 跑步"},
    {"q": "微波炉是怎么加热的？", "domain": "微波炉", "stage": "正题",
     "need": "水分子振动", "conflict": "微波炉 vs 电磁炉"},
    {"q": "微波炉为什么不能放金属？", "domain": "微波炉", "stage": "反题",
     "need": "反射火花", "conflict": "微波炉 vs 电磁炉"},
    {"q": "光合作用产生了什么？", "domain": "光合产物", "stage": "正题",
     "need": "葡萄糖+氧气", "conflict": "光合产物 vs 呼吸产物"},
    {"q": "光合产物和呼吸产物什么区别？", "domain": "光合产物", "stage": "反题",
     "need": "O2 vs CO2", "conflict": "光合产物 vs 呼吸产物"},
    {"q": "什么是数组？", "domain": "数组", "stage": "正题",
     "need": "同类型数据集合", "conflict": "数组 vs 列表"},
    {"q": "数组下标为什么从0开始？", "domain": "数组", "stage": "反题",
     "need": "内存偏移", "conflict": "数组 vs 列表"},
    {"q": "什么是调试？", "domain": "调试", "stage": "正题",
     "need": "定位修复bug", "conflict": "调试 vs 运行错误"},
    {"q": "bug有哪些类型？", "domain": "调试", "stage": "正题",
     "need": "语法/运行时/逻辑", "conflict": "调试 vs 运行错误"},
    {"q": "什么是编程里的类？", "domain": "编程类", "stage": "正题",
     "need": "创建对象的模板", "conflict": "编程类 vs 实例对象"},
    {"q": "类和对象什么区别？", "domain": "编程类", "stage": "反题",
     "need": "模板vs实例", "conflict": "编程类 vs 实例对象"},
    {"q": "什么是编程里的变量？", "domain": "编程变量", "stage": "正题",
     "need": "给数据起名字", "conflict": "编程变量 vs 常量"},
    {"q": "变量为什么叫变量？", "domain": "编程变量", "stage": "反题",
     "need": "可以改变", "conflict": "编程变量 vs 常量"},
    {"q": "什么是编程里的函数？", "domain": "编程函数", "stage": "正题",
     "need": "可复用代码块", "conflict": "编程函数 vs 代码重复"},
    {"q": "函数的参数是什么？", "domain": "编程函数", "stage": "正题",
     "need": "输入", "conflict": "编程函数 vs 代码重复"},
    {"q": "什么是编程里的循环？", "domain": "编程循环", "stage": "正题",
     "need": "重复执行", "conflict": "编程循环 vs 重复代码"},
    {"q": "while循环怎么用？", "domain": "编程循环", "stage": "合题",
     "need": "按条件重复", "conflict": "编程循环 vs 重复代码"},
    {"q": "循环为什么要小心？", "domain": "编程循环", "stage": "反题",
     "need": "防死循环", "conflict": "编程循环 vs 重复代码"},
]
with open(r"D:\Program Files\2_ai\knowledge-base\conflict_testset_v57.json", "w", encoding="utf-8") as f:
    json.dump({"name": "conflict_testset_v57", "conflicts": 15, "items": ITEMS}, f, ensure_ascii=False, indent=1)
print("v57 testset:", len(ITEMS))
