# -*- coding: utf-8 -*-
"""矛盾测试集 v52（12 数学概念·常识迁移 c3）"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")
ITEMS = [
    {"q": "为什么1加1等于2？", "domain": "加法", "stage": "正题",
     "need": "合并计数", "conflict": "加法 vs 数数"},
    {"q": "加法进位是什么？", "domain": "加法", "stage": "反题",
     "need": "满十进一", "conflict": "加法 vs 数数"},
    {"q": "什么是函数？", "domain": "函数定义", "stage": "正题",
     "need": "输入输出对应", "conflict": "函数 vs 变量关系"},
    {"q": "函数是干什么的？", "domain": "函数定义", "stage": "正题",
     "need": "描述变化", "conflict": "函数 vs 变量关系"},
    {"q": "什么是勾股定理？", "domain": "勾股定理", "stage": "正题",
     "need": "a²+b²=c²", "conflict": "勾股定理 vs 直角三角形"},
    {"q": "勾股定理有什么用？", "domain": "勾股定理", "stage": "合题",
     "need": "求边长验直角", "conflict": "勾股定理 vs 直角三角形"},
    {"q": "什么是等差数列？", "domain": "等差数列", "stage": "正题",
     "need": "相邻差相等", "conflict": "等差数列 vs 等比数列"},
    {"q": "怎么求等差数列的和？", "domain": "等差数列", "stage": "合题",
     "need": "首末平均×项数", "conflict": "等差数列 vs 等比数列"},
    {"q": "什么是负数？", "domain": "负数正数", "stage": "正题",
     "need": "比0小", "conflict": "负数 vs 正数"},
    {"q": "负数真实存在吗？", "domain": "负数正数", "stage": "反题",
     "need": "温度欠债海拔", "conflict": "负数 vs 正数"},
    {"q": "0是自然数吗？", "domain": "零自然数", "stage": "正题",
     "need": "现代定义含0", "conflict": "零自然数 vs 正整数"},
    {"q": "0是正整数吗？", "domain": "零自然数", "stage": "反题",
     "need": "正整数从1开始", "conflict": "零自然数 vs 正整数"},
    {"q": "正方形是长方形吗？", "domain": "正方形长方形", "stage": "正题",
     "need": "特殊的长方形", "conflict": "正方形 vs 长方形"},
    {"q": "正方形和长方形什么区别？", "domain": "正方形长方形", "stage": "反题",
     "need": "四边相等", "conflict": "正方形 vs 长方形"},
    {"q": "乘法口诀是什么？", "domain": "乘法口诀", "stage": "正题",
     "need": "九九表", "conflict": "乘法口诀 vs 加法重复"},
    {"q": "三角形面积怎么算？", "domain": "三角形面积", "stage": "正题",
     "need": "底×高÷2", "conflict": "三角形面积 vs 平行四边形"},
    {"q": "为什么三角形面积要除以2？", "domain": "三角形面积", "stage": "反题",
     "need": "两三角拼平行四边", "conflict": "三角形面积 vs 平行四边形"},
    {"q": "什么是分数？", "domain": "分数定义", "stage": "正题",
     "need": "整体的一部分", "conflict": "分数 vs 除法"},
    {"q": "分数和除法什么关系？", "domain": "分数定义", "stage": "反题",
     "need": "a/b=a÷b", "conflict": "分数 vs 除法"},
    {"q": "什么是奇数？", "domain": "奇数", "stage": "正题",
     "need": "除2余1", "conflict": "奇数 vs 偶数"},
    {"q": "奇数加奇数等于什么？", "domain": "奇数", "stage": "合题",
     "need": "偶数", "conflict": "奇数 vs 偶数"},
    {"q": "什么是偶数？", "domain": "偶数", "stage": "正题",
     "need": "除2整除", "conflict": "偶数 vs 奇数"},
    {"q": "0是偶数吗？", "domain": "偶数", "stage": "反题",
     "need": "0能被2整除", "conflict": "偶数 vs 奇数"},
]
with open(r"D:\Program Files\2_ai\knowledge-base\conflict_testset_v52.json", "w", encoding="utf-8") as f:
    json.dump({"name": "conflict_testset_v52", "conflicts": 12, "items": ITEMS}, f, ensure_ascii=False, indent=1)
print("v52 testset:", len(ITEMS))
