# -*- coding: utf-8 -*-
"""round-c5 常识迁移：英语语法概念 6 簇升级（18-28字 → 完整生活直答）
一般现在时/被动语态/名词复数/比较级/定语从句/英语时态
"""
import sys, re, py_compile
sys.stdout.reconfigure(encoding="utf-8")
TRANSLATE_PY = r"C:\Users\FuRongJun\AppData\Local\Programs\Python\Python310\lib\site-packages\wisdom\semantic_translate.py"
src = open(TRANSLATE_PY, encoding="utf-8").read()

ANSWERS = {
"一般现在时": "为什么主语是he要用动词加s、一般现在时怎么用，是『一般现在时』vs『现在进行时』的矛盾——一般现在时（表示（经常发生的事/习惯/事实）、I play（我玩）、He plays（他玩（加s）、第三人称单数（he/she/it/人名）（动词加s/es）、一般现在时（最常见（最基础的时态）——一般现在时的真相：表示习惯/事实/经常发生、第三人称单数（he/she/it）动词加s/es、否定（don't/doesn't）、疑问（Do/Does开头）、规律（其他主语用原形）。真相：①一般现在时是什么——表示习惯事实：一般现在时（表示（经常/习惯/事实/真理）、每天（I go to school every day）、习惯（He plays football（他踢足球）、事实（The sun rises in the east（太阳东升）、真理（Water boils at 100°C）、一般现在时（描述（常态）——一般现在时（习惯/事实/真理（常态描述）；②什么时候动词加s——第三人称单数：主语（第三人称单数（he/she/it/人名/单数名词）、动词（加s（play→plays）、加es（以s/x/ch/sh/o结尾（go→goes）、y变ies（study→studies）、其他主语（I/you/we/they（用原形）、规律（只有三单（加s）——三单加s（he/she/it（go→goes（study→studies（其他用原形）；③一般现在时怎么变否定——don't/doesn't：否定（主语+don't+动词原形（I don't like）、第三人称单数（doesn't+动词原形（He doesn't like）、doesn't（已经带s（后面动词（用原形）、缩略（don't=do not（doesn't=does not）、否定句（动词变回原形）——否定（don't/doesn't+原形（三单用doesn't（动词回原形）；④一般现在时怎么问——Do/Does开头：疑问句（Do+主语+动词原形（Do you like?）、第三人称单数（Does+主语+动词原形（Does he like?）、Does（带s（动词原形）、回答（Yes, I do/No, I don't）、特殊疑问（What do you...?）——疑问（Do/Does+主语+原形（三单Does（动词原形）；⑤一般现在时和现在进行时什么区别——常态vs进行：一般现在时（常态（习惯/事实（I play（我经常玩）、现在进行时（此刻（正在发生（be+doing（I am playing（我正在玩）、一般现在时（often/every day）、进行时（now/right now）、区别（经常做vs正在做）——一般现在时常态（进行时此刻（I play vs I am playing（often vs now）；⑥一般现在时有什么用——描述生活：介绍（I am a student）、习惯（I get up at 7）、爱好（She likes music）、工作（He works in a bank）、事实（The Earth goes around the Sun）、描述（日常/习惯/事实（都用一般现在时）——一般现在时（介绍习惯爱好工作事实（英语基础中的基础）——一般现在时的真相：表示习惯/事实/常态、三单（he/she/it）动词加s/es、否定don't/doesn't+原形、疑问Do/Does+原形、与进行时区别（常态vs正在）、用途（介绍习惯事实）——He plays（他在'一般现在'（经常玩（习惯（一般现在时（英语的'日常模式'（说习惯（说事实（都用它）",
"被动语态": "什么是被动语态、被动语态怎么用，是『被动语态』vs『主动语态』的矛盾——被动语态（是主语（是动作的承受者）、主动（I eat the apple（我吃苹果）、被动（The apple is eaten（苹果被吃）、被动（be+过去分词）、时态（be 变化（is/was/will be）、被动（强调动作的对象（不是谁做的）——被动语态的真相：被动=be+过去分词、主语是承受者、时态体现在be（is eaten/was eaten）、主动强调动作的人（被动强调动作的对象）、中文（被字句（被吃/被打）。真相：①什么是被动语态——动作承受者：被动语态（主语（不是做动作的（是被动作的）、主动（He cleans the room（他打扫房间）、被动（The room is cleaned（房间被打扫）、主语（the room（被打扫（不是打扫者）、被动（be+过去分词（结构）——被动（主语是承受者（The room is cleaned（房间被扫）；②被动语态怎么构成——be+过去分词：被动结构（be+动词过去分词）、一般现在（am/is/are+done（is cleaned）、一般过去（was/were+done（was cleaned）、将来（will be+done（will be cleaned）、进行（being+done（is being cleaned）、完成（have been+done（has been cleaned）、时态（在be上变）——被动结构（be+过去分词（时态变be（is/was/will be）；③什么时候用被动语态——强调承受者：不知道谁做的（The window was broken（窗被打破（不知道谁）、不重要谁做（The cake is made（蛋糕做了）、强调对象（The book was written in 1890）、正式文体（科技/新闻（多用被动）、主动（强调做的人（I wrote the book）——用被动（不知道/不重要谁做（强调对象（新闻科技常用）；④主动变被动怎么变——三步：找宾语（变主语）、be（按新主语和时态）、过去分词（原动词变）、主动（He wrote a book）、被动（A book was written by him）、by+原主语（放在句尾）、宾语变主语（主语变by短语）——主动变被动（宾语变主语（be+过去分词（by+原主语）；⑤被动语态时态怎么变——be 变化：一般现在（is/are+done）、一般过去（was/were+done）、一般将来（will be+done）、现在完成（have/has been+done）、情态（can/must be+done）、口诀（被动时态看be（be随主语时态变）、过去分词（不变）——被动时态（be变化（过去分词不变（is/was/will be+done）；⑥被动语态和主动语态什么区别——强调不同：主动（主语做动作（I eat the apple）、被动（主语被动作（The apple is eaten）、主动（强调谁做）、被动（强调做什么/对象）、中文（被字句（对应被动）、英语（被动（很常用（写作口语）、选择（看强调谁（用主动或被动）——主动强调做的人（被动强调对象（中文被字句对应）——被动语态的真相：be+过去分词、主语是承受者、时态体现在be（is/was/will be）、用被动（不知道/不重要谁做（强调对象）、主动变被动（宾语变主语+be+分词+by）、与主动区别（强调不同）——The room is cleaned（房间被打扫（被动（主语不做事（是被做（be+过去分词（英语的'被字句'（新闻里（文章里（很常见）",
"名词复数": "名词复数怎么变、为什么英语名词有复数，是『名词复数』vs『单数名词』的矛盾——名词复数（表示（两个或以上）、apple→apples（加s）、box→boxes（加es）、baby→babies（y变ies）、一般规则（加s）、特殊（不规则（man→men/child→children）、复数（代表多个）——名词复数的真相：复数表示多个、一般加s（以s/x/ch/sh/o结尾加es、辅音+y变ies、f/fe变ves、不规则（man→men）、复数（谓语用are（三单变复数不用加s）。真相：①名词复数是什么——表示多个：名词复数（表示（两个或更多）、one apple（单数）、two apples（复数）、复数（在单数后（变形）、英语（可数名词（有复数）、不可数（water/milk（没有复数）、复数（代表（多个）——复数表示多个（one apple/two apples（可数名词有复数）；②名词复数一般怎么变——加s：一般（直接加s（book→books/apple→apples）、以s/x/ch/sh结尾（加es（box→boxes/watch→watches）、以辅音+o结尾（加es（tomato→tomatoes）、以辅音+y结尾（y变ies（baby→babies）、以f/fe结尾（变ves（knife→knives）、一般规则（好记）——复数规则（直接加s（s/x/ch/sh加es（y变ies（f变ves）；③名词复数有什么特殊——不规则：man→men（男人）、woman→women（女人）、child→children（孩子）、foot→feet（脚）、tooth→teeth（牙）、mouse→mice（老鼠）、sheep→sheep（羊（不变）、fish→fish（鱼（不变）、不规则复数（要单独记（常见必背）——不规则复数（man→men（child→children（sheep不变（要记）；④可数名词和不可数名词什么区别——能不能数：可数（能数（apples/books（有复数）、不可数（不能数（water/milk/rice（没有复数）、不可数（用much/一些（a little）、可数（用many/几个（a few）、不可数（要量词（a glass of water）、区分（能不能用数字数）——可数有复数（不可数没有（many可数（much不可数（量词搭配）；⑤复数后面谓语怎么变——主谓一致：单数主语（is/plays/has）、复数主语（are/play/have）、The apple is red（单）、The apples are red（复）、三单（加s）在单数（复数不加s（They play）、复数（和单数（谓语不同）——单数is（复数are（三单加s（复数不加（主谓一致）；⑥名词复数有什么用——表达数量：描述多个（I have two books）、问数量（How many apples?）、日常（超市（买水果（复数）、表达（一个和多个（要说清）、复数（是英语（基本规则（必须掌握）——复数表达数量（How many（两个以上（日常必用）——名词复数的真相：复数表示多个、一般加s（s/x/ch/sh加es、y变ies、f变ves）、不规则（man→men/child→children/sheep不变）、可数有复数（不可数没有）、主谓一致（复数用are）、用途（表达数量）——two apples（两个苹果（复数（加个s（多一个（就是复数（英语的'多数'（规则清楚（特殊要记（Sheep 还是 sheep）",
"比较级": "比较级怎么变、为什么有的加er有的用more，是『比较级』vs『最高级』的矛盾——比较级（表示（两者比较（更怎么样）、tall→taller（加er）、beautiful→more beautiful（用more）、短词（加er（tall/old/fast）、长词（用more（beautiful/interesting）、比较级（than（比...）、最高级（三者以上（最...）——比较级的真相：比较级=两者比（更...）、短词加er（taller）、长词用more（more beautiful）、不规则（good→better/bad→worse）、比较级+than（比...更）、最高级（est/most（最...）。真相：①比较级是什么——两者比较：比较级（表示（两者之间（比较（更怎么样）、Tom is taller than Jerry（Tom比Jerry高）、比较（两个（人或物）、比较级（在形容词（变形）、'更'（是关键词（taller更高）、比较级（+than（比）——比较级（两者比（更...（taller than（更高）；②比较级怎么变——加er或more：短词（1-2音节（加er（tall→taller/old→older/fast→faster）、长词（2音节以上（用more（beautiful→more beautiful）、辅音+y（y变ier（happy→happier）、以e结尾（加r（nice→nicer）、重读闭音节（双写尾字母（big→bigger）、规律（短加er（长用more）——比较级（短词加er（长词more（happy→happier（big→bigger）；③为什么不规则——特殊变化：good→better（好→更好）、bad→worse（坏→更坏）、many/much→more（多→更多）、little→less（少→更少）、far→farther/further（远→更远）、不规则（不按规则（要单独记）、better/worse（最常见（必背）——不规则比较级（good→better（bad→worse（more/less（要记）；④比较级后面跟什么——than：比较级（+than（比...）、Tom is taller than Jerry（比Jerry高）、than（连接（比较的对象）、He runs faster than me（比我快）、疑问（Who is taller, Tom or Jerry?）、比较对象（要同类（苹果比苹果）——比较级+than（比...（同类比较（Who is taller?）；⑤比较级和最高级什么区别——两者vs三者：比较级（两者（更（taller）、最高级（三者以上（最（the tallest）、最高级（加est（tallest）或most（most beautiful）、最高级（前面加the）、Tom is the tallest in class（班里最高）、比较级（than）、最高级（in/of+范围）——比较级两者（最高级三者（er vs est（more vs most（the+最高级）；⑥比较级有什么用——生活表达：比身高（I am taller than you）、比价格（This is cheaper than that）、比速度（Faster than light? No）、比较（生活处处（选东西/比大小）、英语口语（比较级（常用）、比较（让表达（更准确）——比较级（比身高价格速度（生活常用（表达更准确）——比较级的真相：两者比（更...）、短词加er（长词more）、不规则（good→better/bad→worse）、比较级+than（比...）、与最高级区别（两者vs三者）、用途（比大小选东西）——taller（更高（两者比（加个er（长的词（用more（好的是better（坏的是worse（比较级（英语的比较'开关'）",
"定语从句": "什么是定语从句、定语从句怎么用，是『定语从句』vs『宾语从句』的矛盾——定语从句（是修饰（名词（的句子）、The book that I bought（我买的那本书）、that/which/who（关系词引导）、修饰名词（先行词）、定语从句（放在（被修饰词后面）、相当于（形容词（修饰名词）——定语从句的真相：定语从句=修饰名词的句子、关系词（that/which/who/whom/whose）、先行词（被修饰的名词）、人用who/that（物用which/that、时间用when（地点用where）、定语从句（让表达更精确）。真相：①什么是定语从句——修饰名词的句子：定语从句（一个句子（修饰名词）、The book that I bought（我买的书）、that I bought（修饰the book）、相当于（一个形容词（修饰名词）、中文（...的（那本我买的书）、定语从句（放在（名词后面）——定语从句（修饰名词的句子（that I bought（'...的'的意思）；②关系词怎么选——看先行词：人（用who/that（the boy who sings）、物（用which/that（the book which I like）、时间（用when（the day when we met）、地点（用where（the school where I study）、原因（用why（the reason why）、所有格（用whose（the girl whose mother is a teacher）、关系词（连接（先行词和从句）——关系词（人who（物which/that（时间when（地点where（所有whose）；③先行词是什么——被修饰的名词：先行词（被定语从句（修饰的名词）、The book that I bought（the book是先行词）、先行词（在从句前面）、关系词（代替先行词（在从句中）、The man who lives next door（the man先行词）、找先行词（先看（被修饰的名词）——先行词（被修饰的名词（关系词代替它（从句中）；④that和which什么区别——用法：that（人和物（都能用）、which（只能物）、人（who/that）、物（which/that）、限制性（that/which（都可）、非限制性（只能用which（逗号隔开）、that（更口语（which（更正式）、现代英语（that常用）——that人+物（which只物（非限制性用which（that口语）；⑤定语从句和宾语从句什么区别——修饰vs内容：定语从句（修饰名词（that book（那本书）、宾语从句（作宾语（I know that he is right（我知道他对）、定语从句（修饰词（如形容词）、宾语从句（作句子成分（如宾语）、先行词（定语从句有（宾语从句没有）、区分（看修饰名词还是作宾语）——定语从句修饰名词（宾语从句作宾语（有先行词vs没有）；⑥定语从句有什么用——表达精确：描述人（The girl who sings well（唱歌好的女孩）、描述物（The phone which I bought（我买的手机）、描述地方（The city where I live（我住的城市）、定语从句（让表达（更具体精确）、写作（用定语从句（句子更丰富）、英语（高级表达（必备）——定语从句（描述人/物/地方（表达更精确（写作必备）——定语从句的真相：修饰名词的句子、关系词（who人/which物/that通用/when时间/where地点）、先行词（被修饰的名词）、that和which区别、与宾语从句区别（修饰vs成分）、用途（表达精确）——The book that I bought（我买的书（that I bought（修饰the book（定语从句（像给名词（穿了个'的'（描述人（描述物（英语的精确表达）",
"英语时态": "英语时态有哪些、时态怎么分，是『英语时态』vs『时态体系』的矛盾——英语时态（是表示（动作发生的时间）、三大类（过去/现在/将来）、每类（又分（一般/进行/完成/完成进行）、一共（12种时态）、一般现在（I play）、现在进行（I am playing）、现在完成（I have played）、一般过去（I played）——英语时态的真相：时态=时间+状态、三大时间（过去/现在/将来）、四种状态（一般/进行/完成/完成进行）、3×4=12种时态、核心（动词变化（体现时态）、常用（前8种）。真相：①英语时态有哪些——12种：三大时间（过去/现在/将来）、四种状态（一般/进行/完成/完成进行）、组合（12种时态）、一般现在（I play）、现在进行（I am playing）、现在完成（I have played）、一般过去（I played）、过去进行（I was playing）、一般将来（I will play）、常用（前6-8种）、12种（全掌握（英语时态通关）——时态12种（3时间×4状态（常用前8）；②时态表示什么——时间+状态：时态（表示（动作的（时间和状态）、时间（过去/现在/将来）、状态（一般/进行/完成/完成进行）、一般（常态/习惯）、进行（正在进行）、完成（已经完成）、完成进行（一直进行到现在）、组合（时间×状态（具体时态）——时态=时间+状态（进行=正在（完成=已经（完成进行=一直进行；③一般现在时什么时候用——习惯事实：一般现在时（习惯（I get up at 7）、事实（The sun rises in the east）、经常（every day/often）、三单（加s（He plays）、一般现在时（最基础（最常用）——一般现在时（习惯事实（every day（三单加s（最基础）；④现在完成时怎么用——已经完成：现在完成（have/has+过去分词）、已经做了（I have finished（我已完成）、持续到现在（I have lived here for 10 years）、过去对现在有影响（I have lost my key（钥匙丢了影响现在）、标志词（already/just/ever/never/for/since）、过去和现在（连接）——现在完成（have+过去分词（已经完成（持续至今（对现在有影响）；⑤时态和动词变化什么关系——动词变形：时态（靠动词（变化体现）、play（原形）、plays（三单）、playing（进行）、played（过去/分词）、be（am/is/are/was/were）、will（将来）、have/has（完成）、动词（是时态的'载体'）、不规则动词（要记（go-went-gone）——时态靠动词变（plays/playing/played（will/have（不规则要记）；⑥怎么学好时态——方法：先学（三大时间（概念）、再学（四种状态（理解）、常用8种（优先掌握）、对比（现在完成vs一般过去）、语境（看时间词（every day/now/yesterday）、练习（造句（说英语（用时态）、时态（是英语（的骨架（慢慢啃）——学时态（先时间后状态（常用8种（看时间词（造句练习）——英语时态的真相：时态=时间+状态（3×4=12种）、时间（过去现在将来）、状态（一般进行完成）、现在完成（have+分词（已做/持续）、动词变化（体现时态）、学好（先时间后状态（常用8种）——I play（现在（I played（过去（I will play（将来（时态（是时间的'照相机'（说过去（说现在（说将来（动词变一变（时间就清楚）",
}

old_answers = {
    "一般现在时": "主语是第三人称单数时，动词一般加s或es",
    "被动语态": "被动语态用be加过去分词，主语是动作的承受者",
    "名词复数": "可数名词复数一般直接加s，以s/x/ch/sh结尾加es",
    "比较级": "比较级一般加er或用more，表示更怎么样",
    "定语从句": "定语从句用关系词引导，修饰前面的名词",
    "英语时态": "英语基本时态分过去、现在、将来三大类",
}
for key, old in old_answers.items():
    print("processing:", key, flush=True)
    found = False
    for m in re.finditer(r'    "%s": "' % key, src):
        line_start = m.start()
        line_end = src.index("\n", line_start)
        line = src[line_start:line_end]
        if old in line:
            src = src[:line_start] + '    "%s": "%s",' % (key, ANSWERS[key]) + src[line_end:]
            found = True
            break
    assert found, f"old answer not found for {key}"

UPD = {
    "一般现在时": ['一般现在时', '第三人称单数', '动词怎么变', '一般现在时是', '三单', '现在时', '经常做什么', 'does', '动词加s', 'habit'],
    "被动语态": ['被动语态', '被动', '被动语态是', '被动句', 'be加过去分词', '被字句', '被动怎么变', '主动变被动', 'passive'],
    "名词复数": ['名词复数', '复数怎么变', '可数名词复数', '复数', '名词变复数', '复数规则', '不可数名词', '复数形式', 'plural'],
    "比较级": ['比较级', '比较级怎么变', '比较级是', 'taller', 'more', 'er结尾', '比较级变化', '不规则比较级', '最高级'],
    "定语从句": ['定语从句', '从句', '定语从句是', '关系词', '先行词', 'that which', 'who whom', '修饰名词', '定语'],
    "英语时态": ['英语时态', '时态有哪些', '时态', '一般现在时', '现在进行时', '现在完成时', '一般过去时', '过去时', '将来时', '12种时态', '时态体系'],
}
for theme, lst in UPD.items():
    m = re.search(r'"%s":\s*\[[^\]]*\]' % theme, src)
    assert m, f"cluster anchor not found: {theme}"
    new = '"%s": [%s]' % (theme, ", ".join('"%s"' % t for t in lst))
    src = src[:m.start()] + new + src[m.end():]

open(TRANSLATE_PY, "w", encoding="utf-8").write(src)
py_compile.compile(TRANSLATE_PY, doraise=True)
print("round-c5 OK: 6 英语语法概念簇升级")
