# -*- coding: utf-8 -*-
p = r'D:\Program Files\2_ai\CommonTrustProtocol\tools\python_code_units.py'
s = open(p, encoding='utf-8').read()
NL = chr(92) + 'n'
Q = chr(34)

unit = [
    '    "数据结构-链表": {',
    '        "task": "链表",',
    '        "pattern": (',
    '            "def linked_list_ops(values, op, value=None):' + NL + Q,
    '            "    # 链表：build 值列表→节点链 / traverse 链→值列表 / contains 查找' + NL + Q,
    '            "    if op == \'build\':' + NL + Q,
    '            "        head = None' + NL + Q,
    '            "        for v in reversed(values):' + NL + Q,
    '            "            head = {\'value\': v, \'next\': head}' + NL + Q,
    '            "        return head' + NL + Q,
    '            "    if op == \'traverse\':' + NL + Q,
    '            "        out = []' + NL + Q,
    '            "        cur = values' + NL + Q,
    '            "        while cur is not None:' + NL + Q,
    '            "            out.append(cur[\'value\'])' + NL + Q,
    '            "            cur = cur[\'next\']' + NL + Q,
    '            "        return out' + NL + Q,
    '            "    if op == \'contains\':' + NL + Q,
    '            "        cur = values' + NL + Q,
    '            "        while cur is not None:' + NL + Q,
    '            "            if cur[\'value\'] == value:' + NL + Q,
    '            "                return True' + NL + Q,
    '            "            cur = cur[\'next\']' + NL + Q,
    '            "        return False' + NL + Q,
    '            "    return None' + NL + '"),',
    '        "cases": [(([1, 2], \'build\'), {\'value\': 1, \'next\': {\'value\': 2, \'next\': None}}),',
    "                  (({'value': 1, 'next': {'value': 2, 'next': None}}, 'traverse'), [1, 2]),",
    "                  (({'value': 1, 'next': {'value': 2, 'next': None}}, 'contains', 2), True),",
    "                  (({'value': 1, 'next': {'value': 2, 'next': None}}, 'contains', 3), False)],",
    '        "params": [],',
    '        "calibration": "对照：单链表——节点链构建/遍历/查找（Python 链表机制）",',
    '    },',
    '    "工具-进制转换": {',
    '        "task": "进制转换",',
    '        "pattern": (',
    '            "def base_convert(value, base, to_text=True):' + NL + Q,
    '            "    # 进制转换：to_text 十进制→base 进制字符串 / 反向解析为十进制' + NL + Q,
    '            "    digits = \'0123456789abcdef\'' + NL + Q,
    '            "    if to_text:' + NL + Q,
    '            "        if value == 0:' + NL + Q,
    '            "            return \'0\'' + NL + Q,
    '            "        out = []' + NL + Q,
    '            "        n = value' + NL + Q,
    '            "        while n > 0:' + NL + Q,
    '            "            out.append(digits[n % base])' + NL + Q,
    '            "            n //= base' + NL + Q,
    '            "        return \'\'.join(reversed(out))' + NL + Q,
    '            "    total = 0' + NL + Q,
    '            "    for ch in value:' + NL + Q,
    '            "        total = total * base + digits.index(ch)' + NL + Q,
    '            "    return total' + NL + '"),',
    '        "cases": [((255, 16, True), \'ff\'),',
    "                  ((10, 2, True), '1010'),",
    "                  (('ff', 16, False), 255),",
    "                  ((0, 8, True), '0'),",
    "                  (('1010', 2, False), 10)],",
    '        "params": [],',
    '        "calibration": "对照：Python bin/oct/hex + int(x, base)——进制双向转换",',
    '    },',
    '    "异常-异常链": {',
    '        "task": "异常链",',
    '        "pattern": (',
    '            "def exception_chain(msg, cause=None):' + NL + Q,
    '            "    # 异常链：包装异常并保留原因（raise from 语义——上下文链）' + NL + Q,
    '            "    e = ValueError(msg)' + NL + Q,
    '            "    if cause is not None:' + NL + Q,
    '            "        e.__cause__ = ValueError(cause)' + NL + Q,
    '            "    return (e.__class__.__name__, str(e),' + NL + Q,
    '            "            str(e.__cause__) if e.__cause__ else None)' + NL + '"),',
    '        "cases": [',
    "            (('外层', '内层'), ('ValueError', '外层', '内层')),",
    "            (('孤立',), ('ValueError', '孤立', None))],",
    '        "params": [],',
    '        "calibration": "对照：Python raise ... from ...——异常链保留原因上下文",',
    '    },',
]
block = '\n'.join(unit) + '\n'
anchor = '\n}\n\n\ndef route_python_unit'
idx = s.rfind(anchor)
assert idx > 0, 'anchor not found'
s = s[:idx] + '\n' + block + '}\n\n\ndef route_python_unit' + s[idx + len(anchor):]
open(p, 'w', encoding='utf-8').write(s)
print('OK appended; new length', len(s.splitlines()), 'lines')
