# -*- coding: utf-8 -*-
"""矛盾关联映射生成：conflict_id → 关联矛盾（含语义说明）。

从 v3 linked 扩展为完整映射 + 人类可读的关联解释，供运行时
「相关矛盾」提示使用。
"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")

# 矛盾 id → 中文名 + 一句话冲突 + 典型追问问题（递归导航用）
CONFLICT_META = {
    "self-lazy": ("自我控制", "想努力 vs 控制不住玩手机", "为什么我总是一边想努力一边控制不住玩手机？"),
    "self-ideal": ("理想现实", "理想 vs 现实差距", "为什么理想和现实的差距这么大？"),
    "self-procrast": ("拖延", "重要事 vs 拖着不做", "为什么越重要的事越拖？"),
    "self-compare": ("攀比", "别人过得好 vs 自己的节奏", "为什么看到别人过得比我好就焦虑？"),
    "fam-couple": ("夫妻协作", "付出 vs 不被看见", "为什么结婚后天天为家务吵架？"),
    "fam-gener": ("代际观念", "年轻人自主 vs 老人观念", "为什么父母总催婚催生？"),
    "fam-motherinlaw": ("婆媳相处", "小家庭主权 vs 婆婆介入", "为什么婆婆总爱插手我们小家庭的事？"),
    "fam-eldercare": ("养老规划", "赡养责任 vs 资源有限", "为什么养老压力全压在我一个人身上？"),
    "fam-remarry": ("重组家庭", "血缘认同 vs 新关系建立", "重组家庭的孩子为什么难相处？"),
    "fam-leftbehind": ("留守儿童", "外出挣钱 vs 孩子缺陪伴", "为什么那么多孩子成了留守儿童？"),
    "edu-score": ("应试压力", "全面发展 vs 分数筛选", "为什么现在的教育都只看分数？"),
    "edu-resource": ("教育公平", "资源集中 vs 公平分配", "为什么学区房这么贵？"),
    "edu-doublecut": ("双减焦虑", "减负 vs 竞争不减", "双减之后为什么家长更焦虑了？"),
    "edu-tutor": ("补习班", "补课投入 vs 效果/抵触", "为什么报了那么多补习班成绩还是上不去？"),
    "teach-authority": ("师生权威", "老师权威 vs 学生质疑", "为什么老师不容许学生质疑？"),
    "teach-fair": ("师生公平", "偏爱优生 vs 放弃差生", "为什么老师总是偏心成绩好的？"),
    "teach-bully": ("校园霸凌", "孩子安全 vs 学校息事宁人", "为什么被欺负了老师也不管？"),
    "work-pay": ("薪酬公平", "干活多 vs 工资低", "为什么干活最多的人工资不是最高？"),
    "work-loyalty": ("跳槽", "忠诚 vs 跳槽发展", "为什么在公司干十年不如跳槽涨得快？"),
    "work-age35": ("中年危机", "经验价值 vs 年龄折价", "为什么35岁就被职场嫌弃？"),
    "work-layoff": ("裁员", "企业降本 vs 员工生存", "为什么公司一不行就裁员？"),
    "work-burnout": ("工作压力", "任务无限 vs 时间有限", "为什么工作永远做不完？"),
    "gov-reg": ("政企监管", "创新速度 vs 监管滞后", "为什么监管总是跟不上创新？"),
    "gov-subsidy": ("产业补贴", "扶持 vs 公平竞争", "为什么政府总补贴某些行业？"),
    "gov-platform": ("平台用工", "灵活就业 vs 权益保障", "为什么外卖骑手没有社保？"),
    "gov-carbon": ("碳中和", "环保成本 vs 企业利润", "为什么环保要求越来越严，工厂怎么办？"),
    "intl-tech": ("技术封锁", "领先者封锁 vs 追赶者自主", "为什么美国要封锁中国芯片？"),
    "intl-trade": ("贸易摩擦", "贸易利益 vs 关税战", "为什么会有贸易战？"),
    "intl-energy": ("能源资源", "能源控制 vs 资源依赖", "为什么石油这么重要，连年打仗都跟它有关？"),
    "intl-climate": ("气候责任", "历史排放 vs 发展权", "为什么减排责任总是谈不拢？"),
    "self-choice": ("选择决策", "理想 vs 稳定", "该选喜欢但不确定的路，还是稳定但无趣的路？"),
    "social-boundary": ("拒绝边界", "合群 vs 做自己", "为什么我总是不会拒绝别人？"),
    "relation-attach": ("依恋焦虑", "亲密 vs 独立", "为什么恋爱中总是患得患失？"),
    "youth-game": ("游戏成瘾", "娱乐需求 vs 学业健康", "为什么孩子一玩游戏就停不下来？"),
    "youth-idol": ("追星", "自我投射 vs 家长观念", "孩子为什么疯狂追星？"),
    "digit-live": ("直播消费", "冲动消费 vs 真实需求", "为什么看直播总忍不住买东西？"),
    "digit-privacy": ("数据隐私", "便利 vs 隐私", "为什么APP什么权限都要？"),
    "soc-aging": ("养老社会", "老龄化 vs 供给不足", "为什么养老金越来越不够用？"),
    "soc-urban": ("城乡流动", "城市贡献 vs 制度壁垒", "为什么在城市打工多年还是没归属感？"),
    "soc-doctor": ("医患关系", "治愈期望 vs 医疗现实", "为什么医患关系越来越紧张？"),
    "soc-consumer": ("消费主义", "物质满足 vs 意义感", "为什么东西越买越多却不快乐？"),
    "soc-lieflat": ("内卷躺平", "努力回报 vs 上升通道", "为什么越来越多人选择躺平？"),
    "family-expect": ("家庭期望", "父母期望 vs 孩子自主", "爸妈总让我考公务员，我不想怎么办？"),
    # v5 新矛盾
    "ai-job": ("AI替代工作", "效率革命 vs 就业冲击", "AI会取代哪些人的工作？"),
    "ai-copyright": ("AI创作版权", "AI训练 vs 创作者版权", "AI用我的画训练，算不算偷？"),
    "ai-bias": ("算法偏见", "算法优化 vs 用户利益", "为什么算法推荐越刷越同质？"),
    "work-free": ("自由职业", "自由 vs 稳定", "自由职业真的自由吗？"),
    "work-remote": ("远程办公", "灵活 vs 协作", "远程办公为什么又爱又恨？"),
    "fam-birth": ("生育成本", "养育成本 vs 生育意愿", "为什么年轻人越来越不想生孩子？"),
    "health-night": ("熬夜", "夜晚自由 vs 健康代价", "为什么明知道熬夜伤身还是戒不掉？"),
    "health-takeout": ("外卖健康", "时间稀缺 vs 健康需要", "为什么天天吃外卖还是戒不掉？"),
    "edu-online": ("网课效果", "便利 vs 学习深度", "为什么网课效果总是不如线下？"),
    "edu-chicken": ("鸡娃", "竞争焦虑 vs 孩子童年", "为什么家长都拼命鸡娃？"),
    # v6 新矛盾
    "law-rights": ("法律维权", "维权成本 vs 权益受损", "为什么维权这么难这么贵？"),
    "health-vaccine": ("疫苗犹豫", "公共健康 vs 个体自主", "为什么有人不愿打疫苗？"),
    "psy-appearance": ("容貌焦虑", "审美标准 vs 自我接纳", "为什么越来越多人容貌焦虑？"),
    "psy-lonely": ("城市孤独", "原子化 vs 归属需要", "为什么越长大越孤独？"),
    "edu-abroad": ("留学选择", "高成本 vs 不确定回报", "留学到底值不值？"),
    "tech-face": ("人脸识别", "便利安全 vs 隐私滥用", "为什么到处都装人脸识别？"),
    "tech-deepfake": ("深度伪造", "技术便利 vs 真实可信", "AI换脸视频为什么这么危险？"),
    "disaster-dev": ("防灾准备", "防灾投入 vs 经济发展", "为什么明知道有风险还在风险区建房？"),
    # v7 新矛盾
    "mil-race": ("军备竞赛", "国家安全 vs 资源浪费", "为什么国家之间要搞军备竞赛？"),
    "mil-proxy": ("代理人战争", "大国克制 vs 小国战场", "为什么大国打仗要借别人的手？"),
    "relig-trad": ("宗教传统", "传承 vs 时代变化", "为什么有些传统和现代生活冲突？"),
    "space-race": ("太空探索", "实力象征 vs 资源争夺", "为什么各国都在抢着登月探火？"),
    "carbon-tax": ("碳税", "减排成本 vs 企业利润", "为什么要收碳税？"),
    "meta-identity": ("元宇宙", "虚拟体验 vs 现实根基", "元宇宙会不会让人更孤独？"),
    "gene-edit": ("基因编辑", "治病希望 vs 伦理风险", "基因编辑治病变态还是危险？"),
    "brain-computer": ("脑机接口", "康复福音 vs 大脑隐私", "脑机接口是福音还是风险？"),
}

# 关联说明（一对矛盾 → 为什么关联）
LINK_NOTES = {
    ("fam-motherinlaw", "fam-couple"): "婆媳矛盾会渗入夫妻关系——丈夫夹中间，夫妻协作被婆婆介入打断",
    ("fam-motherinlaw", "fam-gener"): "婆媳冲突是代际观念冲突在家庭里的具体化",
    ("fam-eldercare", "fam-gener"): "养老分歧本质是代际责任观的冲突",
    ("fam-eldercare", "work-burnout"): "工作压力大时养老责任更难扛——双重负荷",
    ("edu-doublecut", "edu-score"): "双减焦虑源于应试压力没变、补课渠道变了",
    ("edu-tutor", "edu-score"): "补课是应试压力的产物——竞争不变，补课不止",
    ("edu-tutor", "edu-doublecut"): "双减后补习转入地下/私教，焦虑变形",
    ("teach-bully", "teach-fair"): "被霸凌的孩子往往是被忽视的边缘生——公平问题放大",
    ("teach-bully", "fam-couple"): "孩子被欺负的家庭，夫妻常因处理分歧争吵",
    ("work-age35", "work-loyalty"): "跳槽频繁可能加速中年危机（履历碎片化）",
    ("work-age35", "work-burnout"): "中年人的加班压力更高——上有老下有小",
    ("work-layoff", "work-age35"): "裁员优先裁35+——年龄与裁员直接相关",
    ("work-layoff", "work-pay"): "薪酬高的老员工是裁员目标——性价比逻辑",
    ("gov-platform", "gov-reg"): "平台用工乱象正是监管跟不上创新的例子",
    ("gov-platform", "work-pay"): "骑手没社保=劳动报酬权益缺失",
    ("gov-carbon", "gov-subsidy"): "碳中和产业靠补贴起步（新能源补贴）",
    ("gov-carbon", "intl-energy"): "碳中和改变能源格局——影响国际能源争夺",
    ("intl-energy", "intl-tech"): "稀土卡脖子=技术封锁的资源版",
    ("intl-energy", "gov-carbon"): "能源转型（碳中和）重塑国际能源权力",
    ("intl-climate", "gov-carbon"): "国内碳中和与国际减排责任同源",
    ("intl-climate", "intl-energy"): "气候谈判绕不开能源结构（谁排得多）",
    ("self-procrast", "self-lazy"): "拖延是自我控制失败的日常形态",
    ("self-procrast", "work-burnout"): "工作拖延→加班→更累→更拖延，恶性循环",
    ("self-compare", "self-ideal"): "攀比放大理想与现实的落差感",
    ("self-compare", "self-choice"): "看到别人选了稳定/理想，加重自己的纠结",
    # v4 新矛盾关联
    ("fam-remarry", "fam-couple"): "重组家庭的矛盾会冲击夫妻关系（继子女vs新伴侣）",
    ("fam-remarry", "teach-bully"): "重组家庭的孩子更容易成为霸凌对象（身份敏感）",
    ("fam-leftbehind", "fam-eldercare"): "留守背后是父母外出务工——与养老责任同源（都在外挣钱）",
    ("fam-leftbehind", "edu-resource"): "留守儿童的教育资源更薄弱——城乡教育差距的直接受害者",
    ("youth-game", "self-lazy"): "孩子游戏成瘾是自我控制失败的少年版",
    ("youth-game", "edu-score"): "学业压力大，游戏是孩子的逃避出口",
    ("youth-idol", "fam-gener"): "追星是代际观念冲突的新战场（家长不理解饭圈）",
    ("youth-idol", "youth-game"): "追星和游戏同属青少年的精神寄托/逃避渠道",
    ("digit-live", "gov-reg"): "直播乱象是监管跟不上创新的典型案例",
    ("digit-live", "self-lazy"): "冲动消费是即时满足的成年版",
    ("digit-privacy", "gov-platform"): "数据滥用正是平台用工之外的数字平台监管难题",
    ("digit-privacy", "intl-tech"): "数据主权是技术主权的延伸（跨境数据）",
    ("soc-aging", "fam-eldercare"): "社会老龄化放大个人养老压力",
    ("soc-aging", "gov-subsidy"): "养老金缺口需要财政补贴——产业补贴之外的新财政压力",
    ("soc-urban", "fam-leftbehind"): "城乡流动正是留守家庭的成因（父母进城孩子留守）",
    ("soc-urban", "work-layoff"): "流动人口最先受到裁员冲击（没有本地关系网）",
    ("soc-doctor", "work-burnout"): "医生超负荷是工作压力的极端案例",
    ("soc-doctor", "social-boundary"): "医患冲突的根源之一是边界不清（情感卷入）",
    ("soc-consumer", "self-compare"): "消费主义放大攀比（用物品证明自己）",
    ("soc-consumer", "self-ideal"): "买买买填补不了意义感——消费是理想空洞的补偿",
    ("soc-lieflat", "work-age35"): "躺平是35岁危机的提前版（看不到努力回报）",
    ("soc-lieflat", "self-ideal"): "躺平是理想破灭后的反应",
    # v5 新矛盾关联
    ("ai-job", "work-layoff"): "AI替代是裁员的技术版——岗位消失的新形式",
    ("ai-job", "work-age35"): "中年人的经验更易被AI替代（重复经验=可自动化）",
    ("ai-copyright", "digit-privacy"): "AI训练数据与个人数据同属数据主权问题",
    ("ai-copyright", "gov-reg"): "AI版权立法是监管跟不上创新的最新案例",
    ("ai-bias", "digit-privacy"): "算法偏见建立在数据之上——数据有偏则算法有偏",
    ("ai-bias", "teach-fair"): "算法偏见是『评分不公』的机器版（AI评分vs老师偏心）",
    ("work-free", "self-choice"): "选自由职业是理想vs稳定的选择难题",
    ("work-free", "work-layoff"): "被裁后转自由职业是常见路径",
    ("work-remote", "work-burnout"): "远程办公处理不好边界反而更累（永远在线）",
    ("work-remote", "work-loyalty"): "远程稀释组织归属感——影响忠诚度",
    ("fam-birth", "fam-eldercare"): "不生孩子→养老更靠社会资源（个人负担更重）",
    ("fam-birth", "fam-gener"): "催生是代际矛盾的核心（老人催年轻人不生）",
    ("health-night", "self-lazy"): "熬夜是自我控制的夜间失败",
    ("health-night", "work-burnout"): "加班多→报复性熬夜→更累→恶性循环",
    ("health-takeout", "digit-live"): "外卖平台是数字生活的延伸（点单即消费）",
    ("health-takeout", "work-burnout"): "工作强度大→没时间做饭→依赖外卖",
    ("edu-online", "edu-tutor"): "网课是补习班的线上化",
    ("edu-online", "youth-game"): "网课分心与游戏沉迷同源（电子设备诱惑）",
    ("edu-chicken", "edu-doublecut"): "双减后鸡娃转入地下（私教/素质班）",
    ("edu-chicken", "youth-game"): "鸡娃过度→孩子用游戏逃避→新矛盾",
    # v6 新矛盾关联
    ("law-rights", "soc-doctor"): "维权难和看病难同源——公共服务成本高/信息不对称",
    ("law-rights", "gov-reg"): "消费者维权监管不力是监管问题的用户侧",
    ("health-vaccine", "health-takeout"): "疫苗与外卖同属健康决策（公共 vs 个人）",
    ("health-vaccine", "gov-reg"): "防疫政策是监管的公共卫生版",
    ("psy-appearance", "self-compare"): "容貌焦虑是攀比的容貌版",
    ("psy-appearance", "soc-consumer"): "容貌焦虑被消费主义利用（医美/护肤）",
    ("psy-lonely", "soc-urban"): "城市孤独是城乡流动的后果（熟人社会解体）",
    ("psy-lonely", "relation-attach"): "孤独的人更难建立依恋——孤独与亲密互为因果",
    ("edu-abroad", "edu-score"): "留学是应试压力的出口（国内卷不动→出去）",
    ("edu-abroad", "intl-tech"): "留学与技术竞争相关（人才流动/教育竞争）",
    ("tech-face", "digit-privacy"): "人脸识别是数据隐私的生物特征版（脸不可换）",
    ("tech-face", "ai-bias"): "人脸识别对深肤色准确率低——算法偏见案例",
    ("tech-deepfake", "ai-copyright"): "深度伪造与AI创作版权同属AI内容治理",
    ("tech-deepfake", "digit-privacy"): "换脸盗用他人形象=数据隐私的极端滥用",
    ("disaster-dev", "gov-carbon"): "防灾与环保同属『长期安全投入 vs 短期发展』",
    ("disaster-dev", "fam-eldercare"): "灾害对老人冲击最大——防灾与养老交叉",
    # v7 新矛盾关联
    ("mil-race", "intl-tech"): "军备竞赛与技术竞赛同源（军事技术/芯片）",
    ("mil-race", "intl-energy"): "军备竞赛与能源争夺互为因果（资源即战略）",
    ("mil-proxy", "mil-race"): "代理人战争是军备竞赛的战术出口（大国不下场）",
    ("mil-proxy", "intl-trade"): "代理人战争与贸易战都是大国博弈的手段",
    ("relig-trad", "fam-gener"): "代际观念冲突是传统vs现代的微观版",
    ("relig-trad", "intl-climate"): "气候责任谈判也涉及文化价值冲突（发展观）",
    ("space-race", "intl-tech"): "太空竞赛是技术竞赛的延伸（航天=尖端科技）",
    ("space-race", "mil-race"): "太空军事化风险是军备竞赛的太空版",
    ("carbon-tax", "gov-carbon"): "碳税是碳中和的经济手段（政策落地）",
    ("carbon-tax", "intl-climate"): "碳税/碳市场是气候责任谈判的执行层",
    ("meta-identity", "digit-live"): "元宇宙是数字消费的极致形态",
    ("meta-identity", "psy-lonely"): "元宇宙可能加剧城市孤独（虚拟替代现实）",
    ("gene-edit", "tech-deepfake"): "基因编辑与深度伪造同属『技术伦理』前沿",
    ("gene-edit", "gov-reg"): "基因编辑立法是监管滞后于技术的案例",
    ("brain-computer", "digit-privacy"): "脑机接口是数据隐私的终极版（思想数据）",
    ("brain-computer", "tech-face"): "脑机接口与人脸识别同属生物特征技术滥用风险",
}

# 序列化为 JSON（供运行时加载）：conflicts 值改为 dict
out = {"conflicts": {k: {"name": v[0], "conflict": v[1], "q": v[2]}
                     for k, v in CONFLICT_META.items()},
       "links": [{"a": k[0], "b": k[1], "note": v} for k, v in LINK_NOTES.items()]}
with open(r"C:\Users\FuRongJun\AppData\Local\Programs\Python\Python310\lib\site-packages\wisdom\conflict_map.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=1)
print(f"矛盾关联映射: {len(CONFLICT_META)} 矛盾, {len(LINK_NOTES)} 条关联")
for k, v in list(LINK_NOTES.items())[:6]:
    print(f"  {k[0]} <-> {k[1]}: {v[:40]}")
