# -*- coding: utf-8 -*-
"""矛盾关联映射生成：conflict_id → 关联矛盾（含语义说明）。

从 v3 linked 扩展为完整映射 + 人类可读的关联解释，供运行时
「相关矛盾」提示使用。
"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")

# 矛盾 id → 中文名 + 一句话冲突 + 典型追问问题（递归导航用）
CONFLICT_META = {
    "self-lazy": ("自我控制", "想努力 vs 控制不住玩手机", "为什么我总是一边想努力一边控制不住玩手机？"),
    "self-ideal": ("理想现实", "理想 vs 现实差距", "为什么理想和现实的差距这么大？"),
    "self-procrast": ("拖延", "重要事 vs 拖着不做", "为什么越重要的事越拖？"),
    "self-compare": ("攀比", "别人过得好 vs 自己的节奏", "为什么看到别人过得比我好就焦虑？"),
    "fam-couple": ("夫妻协作", "付出 vs 不被看见", "为什么结婚后天天为家务吵架？"),
    "fam-gener": ("代际观念", "年轻人自主 vs 老人观念", "为什么父母总催婚催生？"),
    "fam-motherinlaw": ("婆媳相处", "小家庭主权 vs 婆婆介入", "为什么婆婆总爱插手我们小家庭的事？"),
    "fam-eldercare": ("养老规划", "赡养责任 vs 资源有限", "为什么养老压力全压在我一个人身上？"),
    "fam-remarry": ("重组家庭", "血缘认同 vs 新关系建立", "重组家庭的孩子为什么难相处？"),
    "fam-leftbehind": ("留守儿童", "外出挣钱 vs 孩子缺陪伴", "为什么那么多孩子成了留守儿童？"),
    "edu-score": ("应试压力", "全面发展 vs 分数筛选", "为什么现在的教育都只看分数？"),
    "edu-resource": ("教育公平", "资源集中 vs 公平分配", "为什么学区房这么贵？"),
    "edu-doublecut": ("双减焦虑", "减负 vs 竞争不减", "双减之后为什么家长更焦虑了？"),
    "edu-tutor": ("补习班", "补课投入 vs 效果/抵触", "为什么报了那么多补习班成绩还是上不去？"),
    "teach-authority": ("师生权威", "老师权威 vs 学生质疑", "为什么老师不容许学生质疑？"),
    "teach-fair": ("师生公平", "偏爱优生 vs 放弃差生", "为什么老师总是偏心成绩好的？"),
    "teach-bully": ("校园霸凌", "孩子安全 vs 学校息事宁人", "为什么被欺负了老师也不管？"),
    "work-pay": ("薪酬公平", "干活多 vs 工资低", "为什么干活最多的人工资不是最高？"),
    "work-loyalty": ("跳槽", "忠诚 vs 跳槽发展", "为什么在公司干十年不如跳槽涨得快？"),
    "work-age35": ("中年危机", "经验价值 vs 年龄折价", "为什么35岁就被职场嫌弃？"),
    "work-layoff": ("裁员", "企业降本 vs 员工生存", "为什么公司一不行就裁员？"),
    "work-burnout": ("工作压力", "任务无限 vs 时间有限", "为什么工作永远做不完？"),
    "gov-reg": ("政企监管", "创新速度 vs 监管滞后", "为什么监管总是跟不上创新？"),
    "gov-subsidy": ("产业补贴", "扶持 vs 公平竞争", "为什么政府总补贴某些行业？"),
    "gov-platform": ("平台用工", "灵活就业 vs 权益保障", "为什么外卖骑手没有社保？"),
    "gov-carbon": ("碳中和", "环保成本 vs 企业利润", "为什么环保要求越来越严，工厂怎么办？"),
    "intl-tech": ("技术封锁", "领先者封锁 vs 追赶者自主", "为什么美国要封锁中国芯片？"),
    "intl-trade": ("贸易摩擦", "贸易利益 vs 关税战", "为什么会有贸易战？"),
    "intl-energy": ("能源资源", "能源控制 vs 资源依赖", "为什么石油这么重要，连年打仗都跟它有关？"),
    "intl-climate": ("气候责任", "历史排放 vs 发展权", "为什么减排责任总是谈不拢？"),
    "self-choice": ("选择决策", "理想 vs 稳定", "该选喜欢但不确定的路，还是稳定但无趣的路？"),
    "social-boundary": ("拒绝边界", "合群 vs 做自己", "为什么我总是不会拒绝别人？"),
    "relation-attach": ("依恋焦虑", "亲密 vs 独立", "为什么恋爱中总是患得患失？"),
    "youth-game": ("游戏成瘾", "娱乐需求 vs 学业健康", "为什么孩子一玩游戏就停不下来？"),
    "youth-idol": ("追星", "自我投射 vs 家长观念", "孩子为什么疯狂追星？"),
    "digit-live": ("直播消费", "冲动消费 vs 真实需求", "为什么看直播总忍不住买东西？"),
    "digit-privacy": ("数据隐私", "便利 vs 隐私", "为什么APP什么权限都要？"),
    "soc-aging": ("养老社会", "老龄化 vs 供给不足", "为什么养老金越来越不够用？"),
    "soc-urban": ("城乡流动", "城市贡献 vs 制度壁垒", "为什么在城市打工多年还是没归属感？"),
    "soc-doctor": ("医患关系", "治愈期望 vs 医疗现实", "为什么医患关系越来越紧张？"),
    "soc-consumer": ("消费主义", "物质满足 vs 意义感", "为什么东西越买越多却不快乐？"),
    "soc-lieflat": ("内卷躺平", "努力回报 vs 上升通道", "为什么越来越多人选择躺平？"),
    "family-expect": ("家庭期望", "父母期望 vs 孩子自主", "爸妈总让我考公务员，我不想怎么办？"),
    # v5 新矛盾
    "ai-job": ("AI替代工作", "效率革命 vs 就业冲击", "AI会取代哪些人的工作？"),
    "ai-copyright": ("AI创作版权", "AI训练 vs 创作者版权", "AI用我的画训练，算不算偷？"),
    "ai-bias": ("算法偏见", "算法优化 vs 用户利益", "为什么算法推荐越刷越同质？"),
    "work-free": ("自由职业", "自由 vs 稳定", "自由职业真的自由吗？"),
    "work-remote": ("远程办公", "灵活 vs 协作", "远程办公为什么又爱又恨？"),
    "fam-birth": ("生育成本", "养育成本 vs 生育意愿", "为什么年轻人越来越不想生孩子？"),
    "health-night": ("熬夜", "夜晚自由 vs 健康代价", "为什么明知道熬夜伤身还是戒不掉？"),
    "health-takeout": ("外卖健康", "时间稀缺 vs 健康需要", "为什么天天吃外卖还是戒不掉？"),
    "edu-online": ("网课效果", "便利 vs 学习深度", "为什么网课效果总是不如线下？"),
    "edu-chicken": ("鸡娃", "竞争焦虑 vs 孩子童年", "为什么家长都拼命鸡娃？"),
    # v6 新矛盾
    "law-rights": ("法律维权", "维权成本 vs 权益受损", "为什么维权这么难这么贵？"),
    "health-vaccine": ("疫苗犹豫", "公共健康 vs 个体自主", "为什么有人不愿打疫苗？"),
    "psy-appearance": ("容貌焦虑", "审美标准 vs 自我接纳", "为什么越来越多人容貌焦虑？"),
    "psy-lonely": ("城市孤独", "原子化 vs 归属需要", "为什么越长大越孤独？"),
    "edu-abroad": ("留学选择", "高成本 vs 不确定回报", "留学到底值不值？"),
    "tech-face": ("人脸识别", "便利安全 vs 隐私滥用", "为什么到处都装人脸识别？"),
    "tech-deepfake": ("深度伪造", "技术便利 vs 真实可信", "AI换脸视频为什么这么危险？"),
    "disaster-dev": ("防灾准备", "防灾投入 vs 经济发展", "为什么明知道有风险还在风险区建房？"),
    # v7 新矛盾
    "mil-race": ("军备竞赛", "国家安全 vs 资源浪费", "为什么国家之间要搞军备竞赛？"),
    "mil-proxy": ("代理人战争", "大国克制 vs 小国战场", "为什么大国打仗要借别人的手？"),
    "relig-trad": ("宗教传统", "传承 vs 时代变化", "为什么有些传统和现代生活冲突？"),
    "space-race": ("太空探索", "实力象征 vs 资源争夺", "为什么各国都在抢着登月探火？"),
    "carbon-tax": ("碳税", "减排成本 vs 企业利润", "为什么要收碳税？"),
    "meta-identity": ("元宇宙", "虚拟体验 vs 现实根基", "元宇宙会不会让人更孤独？"),
    "gene-edit": ("基因编辑", "治病希望 vs 伦理风险", "基因编辑治病变态还是危险？"),
    "brain-computer": ("脑机接口", "康复福音 vs 大脑隐私", "脑机接口是福音还是风险？"),
    # v8 新矛盾
    "gen-work": ("职场性别", "历史分工 vs 现代平等", "为什么职场对女性有天花板？"),
    "gen-house": ("家务分工", "隐形劳动 vs 价值衡量", "为什么家务总是女性在做？"),
    "age-digital": ("老年数字", "数字化提速 vs 老人学习减速", "为什么老人用手机这么难？"),
    "edu-job": ("教育就业", "专业滞后 vs 市场变化", "为什么学的东西工作用不上？"),
    "pub-violence": ("网络暴力", "匿名表达 vs 网络伤害", "为什么网上骂人不用负责？"),
    "psy-anxiety": ("心理健康", "心理痛苦 vs 社会污名", "为什么现在抑郁焦虑的人这么多？"),
    "city-share": ("共享单车", "便利 vs 秩序", "为什么共享单车到处都是乱的？"),
    "city-pet": ("城市养宠", "养宠自由 vs 他人安宁", "为什么城市养宠矛盾这么多？"),
    # v9 新矛盾
    "fin-loan": ("消费金融", "超前消费的便利 vs 高息/过度借贷", "为什么网贷这么容易借到？"),
    "food-safe": ("食品安全", "食品工业的添加剂/预制菜 vs 健康担忧", "食品添加剂到底安不安全？"),
    "traffic-e": ("电动车安全", "电动车便利 vs 安全/充电/管理", "为什么电动车起火事故这么多？"),
    "traffic-jam": ("城市拥堵", "私家车便利 vs 拥堵/停车难", "为什么城市越来越堵？"),
    "culture-heritage": ("老字号非遗", "老字号/非遗的传承 vs 市场生存", "为什么老字号越来越少？"),
    "sport-fan": ("体育饭圈", "竞技体育的饭圈化 vs 运动本身", "为什么体育圈也饭圈化了？"),
    "water-res": ("水资源", "水资源短缺 vs 浪费/污染", "为什么水资源越来越紧张？"),
    "plastic-waste": ("塑料污染", "塑料制品便利 vs 白色污染", "为什么限塑令效果不好？"),
    # v10 新矛盾
    "fam-betrothal": ("彩礼", "彩礼习俗 vs 爱情/小家庭负担", "为什么彩礼越来越高？"),
    "fam-parenting": ("丧偶式育儿", "育儿分工 vs 父亲缺席", "为什么育儿都是妈妈的事？"),
    "housing": ("房价", "房价/房贷 vs 居住需求", "为什么房价这么高？"),
    "medical-cost": ("医疗费用", "看病贵 vs 医保/生存", "一场大病为什么能拖垮一个家？"),
    "edu-track": ("教育分流", "中考分流/职高 vs 大学路", "为什么中考就要分流？"),
    "digit-scroll": ("短视频沉迷", "短视频即时快乐 vs 时间/专注", "为什么刷短视频停不下来？"),
    "rural-hollow": ("农村空心化", "进城发展 vs 乡村凋零", "为什么农村年轻人越来越少？"),
    "tourism-trap": ("旅游宰客", "景区商业化/宰客 vs 旅游体验", "为什么景区总宰客？"),
    # v11 新矛盾
    "emp-pua": ("职场PUA", "老板画饼/贬低 vs 自我价值", "为什么老板总爱画饼？"),
    "health-weight": ("身材焦虑", "身材标准 vs 健康/自我接纳", "为什么越来越多人身材焦虑？"),
    "public-civility": ("公共文明", "公共场所熊孩子/噪音 vs 个人自由", "为什么高铁上总有熊孩子？"),
    "edu-punish": ("教育惩戒", "打骂/惩罚 vs 讲道理/边界", "孩子不打不成器吗？"),
    "study-kaoyan": ("考研考公", "稳定追求 vs 竞争/内卷", "为什么越来越多人考研考公？"),
    "fam-solitude": ("独居老人", "老人独居 vs 子女陪伴/照护", "为什么老人越来越孤独？"),
    "food-residue": ("农药残留", "吃得安全 vs 有机太贵", "蔬菜水果都有农药残留吗？"),
    "city-elevator": ("老旧小区", "加装电梯/改造 vs 费用/利益分歧", "为什么老小区加装电梯这么难？"),
    # v12 新矛盾
    "edu-graduate": ("应届生就业", "毕业就失业 vs 岗位需求错配", "为什么毕业就失业？"),
    "digit-scam": ("电信诈骗", "诈骗手段升级 vs 老人防范薄弱", "为什么老人容易被骗？"),
    "digit-tipping": ("直播打赏", "打赏主播 vs 钱/理性", "为什么有人花那么多钱打赏？"),
    "med-cosmetic": ("医美整容", "变美需求 vs 手术风险", "为什么越来越多人整容？"),
    "fam-yuesao": ("月嫂月子", "请月嫂花钱 vs 家人带/值不值", "为什么月嫂这么贵？"),
    "health-myopia": ("儿童近视", "电子产品/作业 vs 视力保护", "为什么孩子近视越来越多？"),
    "city-square": ("广场舞", "老人健身需求 vs 周边安宁", "为什么广场舞总有矛盾？"),
    "food-waste": ("光盘行动", "面子/点多了 vs 粮食浪费", "为什么浪费食物这么普遍？"),
    # v13 新矛盾
    "soc-declutter": ("断舍离", "囤积/留着 vs 断舍离/极简", "为什么东西越攒越多？"),
    "pet-medical": ("宠物医疗", "宠物看病贵 vs 弃养/值不值", "为什么宠物看病这么贵？"),
    "fam-date": ("相亲条件", "相亲看条件 vs 感情", "为什么相亲都看条件？"),
    "social-toast": ("酒桌文化", "劝酒 vs 健康/自愿", "为什么酒桌总要劝酒？"),
    "edu-driving": ("学车驾考", "驾校乱象 vs 拿证刚需", "为什么驾校教练这么凶？"),
    "city-accessibility": ("无障碍出行", "残障出行 vs 设施不足/占用", "为什么盲道总被占用？"),
    "work-rehire": ("退休再就业", "退休后再就业 vs 年龄/体面", "为什么退休了还想找工作？"),
    "env-sort": ("垃圾分类", "分类麻烦 vs 环境收益", "为什么垃圾分类这么麻烦？"),
    # v14 新矛盾
    "fam-wedding": ("婚庆消费", "结婚花钱 vs 简办/面子", "为什么结婚这么贵？"),
    "soc-secondhand": ("二手交易", "二手买卖 vs 假货/纠纷", "为什么二手平台这么火？"),
    "disaster-drill": ("应急演练", "演练形式化 vs 真有用", "为什么演练总是走过场？"),
    "fam-housekeeper": ("家政服务", "请保姆 vs 信任/隐私", "为什么好保姆这么难找？"),
    "fin-wealth": ("理财推销", "理财收益 vs 亏损风险", "为什么银行也卖理财产品？"),
    "city-property": ("小区物业", "物业费 vs 服务质量", "为什么物业费年年涨？"),
    "health-smoke": ("公共场所吸烟", "吸烟自由 vs 他人健康", "为什么公共场合总有人抽烟？"),
    "digit-dating": ("网络交友", "网恋缘分 vs 杀猪盘", "为什么网恋容易翻车？"),
    # v15 新矛盾
    "psy-single": ("独居青年", "独居自由 vs 孤独/生活管理", "为什么越来越多人独居？"),
    "edu-trainingloan": ("培训贷", "培训先贷款 vs 就业承诺", "为什么培训总是先贷款？"),
    "edu-gaokao": ("高考复读", "复读一年 vs 青春/风险", "为什么越来越多人复读？"),
    "fam-grandparenting": ("隔代育儿", "老人带娃 vs 父母教育理念", "为什么老人总要插手带娃？"),
    "digit-phone": ("旧手机回收", "旧手机处理 vs 数据隐私/浪费", "旧手机怎么处理？"),
    "soc-tuango": ("社区团购", "团购便宜 vs 菜市场/品质", "为什么社区团购这么便宜？"),
    "traffic-trainfood": ("高铁餐饮", "高铁盒饭贵 vs 自带/垄断", "为什么高铁盒饭这么贵？"),
    "edu-allowance": ("儿童零花钱", "零花钱 vs 惯坏/理财教育", "该不该给孩子零花钱？"),
    # v16 新矛盾
    "edu-parttime": ("大学生兼职", "兼职赚钱 vs 学业时间", "为什么大学生都在兼职？"),
    "fam-elderlove": ("中老年婚恋", "父母再婚 vs 子女态度/财产", "为什么老人也想找老伴？"),
    "pet-funeral": ("宠物殡葬", "宠物离世 vs 处理方式", "宠物离世怎么处理？"),
    "soc-reading": ("图书阅读", "读书 vs 手机碎片化", "为什么越来越多人不读书了？"),
    "logistics-station": ("快递驿站", "驿站取件 vs 送货上门", "为什么快递都不送上门了？"),
    "traffic-eldercar": ("老年代步车", "代步车 vs 安全/管理", "为什么老年代步车这么多？"),
    "edu-hobby": ("儿童兴趣班", "兴趣班 vs 孩子意愿/玩", "为什么孩子都在上兴趣班？"),
    "tourism-hotel": ("酒店卫生", "酒店卫生 vs 成本", "酒店卫生真的干净吗？"),
    # v17 新矛盾
    "traffic-ridehailing": ("网约车安全", "网约车便利 vs 安全/司机权益", "网约车安全吗？"),
    "fitness-card": ("健身房跑路", "办卡优惠 vs 跑路风险", "为什么健身房总跑路？"),
    "traffic-charge": ("充电桩安装", "装桩需求 vs 物业/安全阻力", "为什么装充电桩这么难？"),
    "city-library": ("图书馆占座", "占座 vs 座位资源", "为什么图书馆总有人占座？"),
    "health-height": ("儿童身高焦虑", "比身高 vs 科学/个体差异", "为什么家长都焦虑孩子身高？"),
    "pet-boarding": ("宠物寄养", "寄养费用 vs 宠物应激/靠谱", "为什么宠物寄养这么贵？"),
    "fam-giftmoney": ("随份子", "人情往来 vs 经济负担", "为什么份子钱越随越多？"),
    "culture-ticket": ("演唱会抢票", "抢票难 vs 黄牛溢价", "为什么演唱会票这么难抢？"),
}

# 关联说明（一对矛盾 → 为什么关联）
LINK_NOTES = {
    ("fam-motherinlaw", "fam-couple"): "婆媳矛盾会渗入夫妻关系——丈夫夹中间，夫妻协作被婆婆介入打断",
    ("fam-motherinlaw", "fam-gener"): "婆媳冲突是代际观念冲突在家庭里的具体化",
    ("fam-eldercare", "fam-gener"): "养老分歧本质是代际责任观的冲突",
    ("fam-eldercare", "work-burnout"): "工作压力大时养老责任更难扛——双重负荷",
    ("edu-doublecut", "edu-score"): "双减焦虑源于应试压力没变、补课渠道变了",
    ("edu-tutor", "edu-score"): "补课是应试压力的产物——竞争不变，补课不止",
    ("edu-tutor", "edu-doublecut"): "双减后补习转入地下/私教，焦虑变形",
    ("teach-bully", "teach-fair"): "被霸凌的孩子往往是被忽视的边缘生——公平问题放大",
    ("teach-bully", "fam-couple"): "孩子被欺负的家庭，夫妻常因处理分歧争吵",
    ("work-age35", "work-loyalty"): "跳槽频繁可能加速中年危机（履历碎片化）",
    ("work-age35", "work-burnout"): "中年人的加班压力更高——上有老下有小",
    ("work-layoff", "work-age35"): "裁员优先裁35+——年龄与裁员直接相关",
    ("work-layoff", "work-pay"): "薪酬高的老员工是裁员目标——性价比逻辑",
    ("gov-platform", "gov-reg"): "平台用工乱象正是监管跟不上创新的例子",
    ("gov-platform", "work-pay"): "骑手没社保=劳动报酬权益缺失",
    ("gov-carbon", "gov-subsidy"): "碳中和产业靠补贴起步（新能源补贴）",
    ("gov-carbon", "intl-energy"): "碳中和改变能源格局——影响国际能源争夺",
    ("intl-energy", "intl-tech"): "稀土卡脖子=技术封锁的资源版",
    ("intl-energy", "gov-carbon"): "能源转型（碳中和）重塑国际能源权力",
    ("intl-climate", "gov-carbon"): "国内碳中和与国际减排责任同源",
    ("intl-climate", "intl-energy"): "气候谈判绕不开能源结构（谁排得多）",
    ("self-procrast", "self-lazy"): "拖延是自我控制失败的日常形态",
    ("self-procrast", "work-burnout"): "工作拖延→加班→更累→更拖延，恶性循环",
    ("self-compare", "self-ideal"): "攀比放大理想与现实的落差感",
    ("self-compare", "self-choice"): "看到别人选了稳定/理想，加重自己的纠结",
    # v4 新矛盾关联
    ("fam-remarry", "fam-couple"): "重组家庭的矛盾会冲击夫妻关系（继子女vs新伴侣）",
    ("fam-remarry", "teach-bully"): "重组家庭的孩子更容易成为霸凌对象（身份敏感）",
    ("fam-leftbehind", "fam-eldercare"): "留守背后是父母外出务工——与养老责任同源（都在外挣钱）",
    ("fam-leftbehind", "edu-resource"): "留守儿童的教育资源更薄弱——城乡教育差距的直接受害者",
    ("youth-game", "self-lazy"): "孩子游戏成瘾是自我控制失败的少年版",
    ("youth-game", "edu-score"): "学业压力大，游戏是孩子的逃避出口",
    ("youth-idol", "fam-gener"): "追星是代际观念冲突的新战场（家长不理解饭圈）",
    ("youth-idol", "youth-game"): "追星和游戏同属青少年的精神寄托/逃避渠道",
    ("digit-live", "gov-reg"): "直播乱象是监管跟不上创新的典型案例",
    ("digit-live", "self-lazy"): "冲动消费是即时满足的成年版",
    ("digit-privacy", "gov-platform"): "数据滥用正是平台用工之外的数字平台监管难题",
    ("digit-privacy", "intl-tech"): "数据主权是技术主权的延伸（跨境数据）",
    ("soc-aging", "fam-eldercare"): "社会老龄化放大个人养老压力",
    ("soc-aging", "gov-subsidy"): "养老金缺口需要财政补贴——产业补贴之外的新财政压力",
    ("soc-urban", "fam-leftbehind"): "城乡流动正是留守家庭的成因（父母进城孩子留守）",
    ("soc-urban", "work-layoff"): "流动人口最先受到裁员冲击（没有本地关系网）",
    ("soc-doctor", "work-burnout"): "医生超负荷是工作压力的极端案例",
    ("soc-doctor", "social-boundary"): "医患冲突的根源之一是边界不清（情感卷入）",
    ("soc-consumer", "self-compare"): "消费主义放大攀比（用物品证明自己）",
    ("soc-consumer", "self-ideal"): "买买买填补不了意义感——消费是理想空洞的补偿",
    ("soc-lieflat", "work-age35"): "躺平是35岁危机的提前版（看不到努力回报）",
    ("soc-lieflat", "self-ideal"): "躺平是理想破灭后的反应",
    # v5 新矛盾关联
    ("ai-job", "work-layoff"): "AI替代是裁员的技术版——岗位消失的新形式",
    ("ai-job", "work-age35"): "中年人的经验更易被AI替代（重复经验=可自动化）",
    ("ai-copyright", "digit-privacy"): "AI训练数据与个人数据同属数据主权问题",
    ("ai-copyright", "gov-reg"): "AI版权立法是监管跟不上创新的最新案例",
    ("ai-bias", "digit-privacy"): "算法偏见建立在数据之上——数据有偏则算法有偏",
    ("ai-bias", "teach-fair"): "算法偏见是『评分不公』的机器版（AI评分vs老师偏心）",
    ("work-free", "self-choice"): "选自由职业是理想vs稳定的选择难题",
    ("work-free", "work-layoff"): "被裁后转自由职业是常见路径",
    ("work-remote", "work-burnout"): "远程办公处理不好边界反而更累（永远在线）",
    ("work-remote", "work-loyalty"): "远程稀释组织归属感——影响忠诚度",
    ("fam-birth", "fam-eldercare"): "不生孩子→养老更靠社会资源（个人负担更重）",
    ("fam-birth", "fam-gener"): "催生是代际矛盾的核心（老人催年轻人不生）",
    ("health-night", "self-lazy"): "熬夜是自我控制的夜间失败",
    ("health-night", "work-burnout"): "加班多→报复性熬夜→更累→恶性循环",
    ("health-takeout", "digit-live"): "外卖平台是数字生活的延伸（点单即消费）",
    ("health-takeout", "work-burnout"): "工作强度大→没时间做饭→依赖外卖",
    ("edu-online", "edu-tutor"): "网课是补习班的线上化",
    ("edu-online", "youth-game"): "网课分心与游戏沉迷同源（电子设备诱惑）",
    ("edu-chicken", "edu-doublecut"): "双减后鸡娃转入地下（私教/素质班）",
    ("edu-chicken", "youth-game"): "鸡娃过度→孩子用游戏逃避→新矛盾",
    # v6 新矛盾关联
    ("law-rights", "soc-doctor"): "维权难和看病难同源——公共服务成本高/信息不对称",
    ("law-rights", "gov-reg"): "消费者维权监管不力是监管问题的用户侧",
    ("health-vaccine", "health-takeout"): "疫苗与外卖同属健康决策（公共 vs 个人）",
    ("health-vaccine", "gov-reg"): "防疫政策是监管的公共卫生版",
    ("psy-appearance", "self-compare"): "容貌焦虑是攀比的容貌版",
    ("psy-appearance", "soc-consumer"): "容貌焦虑被消费主义利用（医美/护肤）",
    ("psy-lonely", "soc-urban"): "城市孤独是城乡流动的后果（熟人社会解体）",
    ("psy-lonely", "relation-attach"): "孤独的人更难建立依恋——孤独与亲密互为因果",
    ("edu-abroad", "edu-score"): "留学是应试压力的出口（国内卷不动→出去）",
    ("edu-abroad", "intl-tech"): "留学与技术竞争相关（人才流动/教育竞争）",
    ("tech-face", "digit-privacy"): "人脸识别是数据隐私的生物特征版（脸不可换）",
    ("tech-face", "ai-bias"): "人脸识别对深肤色准确率低——算法偏见案例",
    ("tech-deepfake", "ai-copyright"): "深度伪造与AI创作版权同属AI内容治理",
    ("tech-deepfake", "digit-privacy"): "换脸盗用他人形象=数据隐私的极端滥用",
    ("disaster-dev", "gov-carbon"): "防灾与环保同属『长期安全投入 vs 短期发展』",
    ("disaster-dev", "fam-eldercare"): "灾害对老人冲击最大——防灾与养老交叉",
    # v7 新矛盾关联
    ("mil-race", "intl-tech"): "军备竞赛与技术竞赛同源（军事技术/芯片）",
    ("mil-race", "intl-energy"): "军备竞赛与能源争夺互为因果（资源即战略）",
    ("mil-proxy", "mil-race"): "代理人战争是军备竞赛的战术出口（大国不下场）",
    ("mil-proxy", "intl-trade"): "代理人战争与贸易战都是大国博弈的手段",
    ("relig-trad", "fam-gener"): "代际观念冲突是传统vs现代的微观版",
    ("relig-trad", "intl-climate"): "气候责任谈判也涉及文化价值冲突（发展观）",
    ("space-race", "intl-tech"): "太空竞赛是技术竞赛的延伸（航天=尖端科技）",
    ("space-race", "mil-race"): "太空军事化风险是军备竞赛的太空版",
    ("carbon-tax", "gov-carbon"): "碳税是碳中和的经济手段（政策落地）",
    ("carbon-tax", "intl-climate"): "碳税/碳市场是气候责任谈判的执行层",
    ("meta-identity", "digit-live"): "元宇宙是数字消费的极致形态",
    ("meta-identity", "psy-lonely"): "元宇宙可能加剧城市孤独（虚拟替代现实）",
    ("gene-edit", "tech-deepfake"): "基因编辑与深度伪造同属『技术伦理』前沿",
    ("gene-edit", "gov-reg"): "基因编辑立法是监管滞后于技术的案例",
    ("brain-computer", "digit-privacy"): "脑机接口是数据隐私的终极版（思想数据）",
    ("brain-computer", "tech-face"): "脑机接口与人脸识别同属生物特征技术滥用风险",
    # v8 新矛盾关联
    ("gen-work", "work-pay"): "职场性别不平等的核心是薪酬/晋升歧视",
    ("gen-work", "fam-birth"): "生育成本是职场性别歧视的根源（产假顾虑）",
    ("gen-house", "fam-couple"): "家务分工失衡是夫妻矛盾的日常形态",
    ("gen-house", "work-pay"): "隐形家务不产生工资=价值被低估（与薪酬同理）",
    ("age-digital", "digit-privacy"): "老人是数字风险最脆弱人群（易被骗/不会维权）",
    ("age-digital", "fam-eldercare"): "老人数字鸿沟放大养老困难（挂号/支付/联系）",
    ("edu-job", "edu-score"): "教育错配源于应试导向（为分数不为能力）",
    ("edu-job", "work-layoff"): "学非所用者在裁员中最脆弱（技能不匹配）",
    ("pub-violence", "digit-privacy"): "网暴常伴随人肉搜索（隐私泄露）",
    ("pub-violence", "psy-appearance"): "网暴击中的是人的外貌/身份（容貌攻击）",
    ("psy-anxiety", "psy-lonely"): "孤独是焦虑抑郁的温床",
    ("psy-anxiety", "work-burnout"): "工作压力积累成心理问题",
    ("city-share", "gov-reg"): "共享单车乱象是监管滞后于新业态的案例",
    ("city-share", "soc-urban"): "共享单车是城市化便利的产物",
    ("city-pet", "social-boundary"): "养宠矛盾本质是边界问题（自由vs他人）",
    ("city-pet", "psy-lonely"): "养宠是孤独的解药——孤独者更需要宠物",
    # v9 新矛盾关联
    ("fin-loan", "digit-live"): "直播冲动消费是借贷的入口——先买后还，消费失控进阶为负债",
    ("fin-loan", "soc-consumer"): "消费主义驱动超前消费——『想要』被包装成『需要』",
    ("food-safe", "health-takeout"): "外卖是预制菜/添加剂的主要场景——方便与健康的同一战场",
    ("food-safe", "gov-reg"): "食品安全监管是『管得住黑心 vs 管不死行业』的监管难题",
    ("traffic-e", "city-share"): "电动车与共享出行同属城市出行新形态——便利与管理的拉扯",
    ("traffic-e", "gov-reg"): "电动车充电/电池标准是监管滞后于新业态的案例",
    ("traffic-jam", "soc-urban"): "城市化（人口聚集）是拥堵的结构性根源",
    ("traffic-jam", "gov-reg"): "限号/停车管理是治理型监管的日常形态",
    ("culture-heritage", "relig-trad"): "老字号与宗教传统同属『传统 vs 现代』的文化冲突",
    ("culture-heritage", "soc-consumer"): "消费主义冲击老字号（快餐/网红店 vs 老味道）",
    ("sport-fan", "youth-idol"): "体育饭圈化是追星文化的体育版——偶像逻辑入侵竞技",
    ("sport-fan", "pub-violence"): "饭圈互撕/网暴运动员是网络暴力的竞技场形态",
    ("water-res", "gov-carbon"): "水与碳同属资源环境治理——环保投入 vs 发展成本",
    ("water-res", "disaster-dev"): "干旱/水灾是水资源矛盾的灾害化——防灾与用水同源",
    ("plastic-waste", "gov-carbon"): "限塑与碳中和同属环保政策——个体便利 vs 长期环境",
    ("plastic-waste", "health-takeout"): "外卖是塑料垃圾最大来源——外卖便利的两头代价",
    # v10 新矛盾关联
    ("fam-betrothal", "fam-gener"): "彩礼是代际观念冲突的婚嫁形态（老人要面子/年轻人要小家庭）",
    ("fam-betrothal", "fam-couple"): "彩礼谈不拢直接冲击小家庭——婚前的账婚后来算",
    ("fam-parenting", "gen-house"): "丧偶式育儿是家务分工失衡的育儿版（隐形劳动+缺席）",
    ("fam-parenting", "fam-couple"): "育儿分工不公是夫妻矛盾的高发点",
    ("housing", "fam-birth"): "房价/房贷是生育成本的大头——买不起房就不敢生",
    ("housing", "soc-urban"): "城市化推高房价，房价又反过来挤压进城者（城乡流动困境）",
    ("medical-cost", "soc-doctor"): "看病贵是医患关系的经济根源（费用纠纷）",
    ("medical-cost", "soc-aging"): "老龄化放大医疗费用压力（老人大病多/医保承压）",
    ("edu-track", "edu-score"): "分流是应试筛选的节点化（分数决定去普高还是职高）",
    ("edu-track", "edu-job"): "职高出路窄正是教育就业错配的表现（学技能没回报）",
    ("digit-scroll", "self-lazy"): "刷短视频是自我控制的数字版失败（即时满足）",
    ("digit-scroll", "youth-game"): "短视频与游戏同属数字沉迷——争夺注意力同一战场",
    ("rural-hollow", "soc-urban"): "农村空心化是城乡流动的另一面（人往城里走，农村变空）",
    ("rural-hollow", "fam-leftbehind"): "年轻人进城=孩子留守+老人空巢——空心化的家庭代价",
    ("tourism-trap", "gov-reg"): "宰客乱象是监管滞后于市场逐利的案例（处罚太轻/执法难）",
    ("tourism-trap", "soc-consumer"): "旅游消费是消费主义的移动版（为体验付费/被套路收割）",
    # v11 新矛盾关联
    ("emp-pua", "work-burnout"): "职场PUA叠加工作压力——身心双重消耗",
    ("emp-pua", "social-boundary"): "不会拒绝的人更容易被PUA（不敢反驳/不敢走）",
    ("health-weight", "psy-appearance"): "身材焦虑是容貌焦虑的身体版（同一审美暴力）",
    ("health-weight", "health-takeout"): "外卖高油高糖是身材焦虑的现实诱因（吃了胖→焦虑→更焦虑）",
    ("public-civility", "city-pet"): "公共场所矛盾与养宠矛盾同源——个人自由 vs 他人安宁",
    ("public-civility", "social-boundary"): "公共边界是『拒绝边界』的公共版（学会说不/学会守界）",
    ("edu-punish", "teach-authority"): "打骂式管教是老师权威的家庭版（我打你=我是为你好）",
    ("edu-punish", "youth-game"): "管太严/打骂把孩子推向游戏世界（逃避现实）",
    ("study-kaoyan", "edu-job"): "考研考公热是教育就业错配的结果（学历贬值→追求稳定）",
    ("study-kaoyan", "soc-lieflat"): "考公热与躺平同源——对上升通道失望后的防御选择",
    ("fam-solitude", "fam-eldercare"): "独居是养老问题的日常形态（钱之外还要陪伴）",
    ("fam-solitude", "soc-aging"): "老龄化放大独居问题（独居老人比例持续上升）",
    ("food-residue", "food-safe"): "农药残留与添加剂同属食品安全焦虑（看得见的怕+看不见的怕）",
    ("food-residue", "medical-cost"): "吃得不安心→身体担忧→医疗负担（预防焦虑的链条）",
    ("city-elevator", "housing"): "老小区改造是居住问题的存量版（买不起新房→改造旧房）",
    ("city-elevator", "gov-subsidy"): "加装电梯补贴是政府扶持公共品的案例（民生投入）",
    # v12 新矛盾关联
    ("edu-graduate", "edu-job"): "应届生就业难是教育就业错配的第一现场（毕业即暴露）",
    ("edu-graduate", "study-kaoyan"): "就业难驱动考研考公（延缓就业/追求稳定）",
    ("digit-scam", "age-digital"): "老人被骗是数字鸿沟的代价（不会识别/不敢质疑）",
    ("digit-scam", "digit-privacy"): "诈骗依赖个人信息泄露（精准诈骗=隐私滥用）",
    ("digit-tipping", "digit-live"): "打赏与直播购物同属直播经济——冲动消费的数字版",
    ("digit-tipping", "youth-idol"): "打赏是追星经济的直播版（为偶像花钱）",
    ("med-cosmetic", "psy-appearance"): "整容是容貌焦虑的极端解决（外貌焦虑→动刀）",
    ("med-cosmetic", "medical-cost"): "医美是健康消费的高风险区（手术有风险/失败维权难）",
    ("fam-yuesao", "fam-birth"): "月嫂贵是生育成本的一部分（生得起养不起的细节）",
    ("fam-yuesao", "fam-parenting"): "月嫂是育儿分工的市场化（专业外包 vs 家庭承担）",
    ("health-myopia", "digit-scroll"): "孩子近视与刷屏沉迷同源（屏幕时间失控）",
    ("health-myopia", "edu-score"): "学业负担挤压户外时间——应试压力的身体代价",
    ("city-square", "public-civility"): "广场舞之争是公共边界矛盾的社区版",
    ("city-square", "fam-solitude"): "广场舞是老人的社交出口——孤独的广场解法",
    ("food-waste", "plastic-waste"): "光盘与限塑同属资源节约（粮食/塑料都不该浪费）",
    ("food-waste", "soc-consumer"): "浪费是消费主义的面子版（丰盛崇拜）",
    # v13 新矛盾关联
    ("soc-declutter", "soc-consumer"): "断舍离是消费主义的反向运动（买买买的反面是扔扔扔）",
    ("soc-declutter", "digit-live"): "直播冲动消费囤积的源头——买的时候爽，囤的时候愁",
    ("pet-medical", "city-pet"): "宠物医疗是养宠责任的经济面（养得起更要治得起）",
    ("pet-medical", "medical-cost"): "宠物看病贵与人生病贵同构（医疗成本结构）",
    ("fam-date", "fam-betrothal"): "相亲看条件与彩礼谈钱同源——婚姻的物质基础之争",
    ("fam-date", "relation-attach"): "相亲是依恋关系的条件入口（先匹配再动心）",
    ("social-toast", "work-age35"): "职场应酬是中年人的酒桌主场（躲不掉的局）",
    ("social-toast", "social-boundary"): "不会拒绝的人最容易被劝酒——拒酒是边界训练",
    ("edu-driving", "edu-job"): "驾照是就业的隐形门槛（很多岗位要求会开车）",
    ("edu-driving", "gov-reg"): "驾校乱象是监管滞后于市场逐利的案例",
    ("city-accessibility", "age-digital"): "无障碍与适老化同源——弱势群体的出行/数字权利",
    ("city-accessibility", "city-elevator"): "无障碍设施与加装电梯同属城市适老化改造",
    ("work-rehire", "work-age35"): "退休再就业难是35岁门槛的延长版（年龄歧视贯穿一生）",
    ("work-rehire", "soc-aging"): "老龄化让银发劳动力成为社会议题（老有所为）",
    ("env-sort", "plastic-waste"): "垃圾分类是塑料治理的执行环节（分出来才能回收）",
    ("env-sort", "gov-reg"): "分类政策是监管型治理（前端立法+后端执法）",
    # v14 新矛盾关联
    ("fam-wedding", "fam-betrothal"): "婚礼消费与彩礼同属婚姻成本（结婚要花的钱越来越多）",
    ("fam-wedding", "soc-consumer"): "婚礼是消费主义的人生巅峰场景（一生一次的营销）",
    ("soc-secondhand", "digit-live"): "二手交易是直播冲动消费的补救（买多了→闲鱼见）",
    ("soc-secondhand", "gov-reg"): "二手平台假货纠纷是监管新课题（C2C交易难追责）",
    ("disaster-drill", "disaster-dev"): "演练是防灾投入的落地环节（钱要花在练上）",
    ("disaster-drill", "edu-score"): "走过场式演练与应试教育同构（重形式轻实效）",
    ("fam-housekeeper", "gen-house"): "家政是家务分工的市场化（外包还是内部消化）",
    ("fam-housekeeper", "fam-couple"): "请保姆/老人带娃影响夫妻协作（家务谁负责之争）",
    ("fin-wealth", "fin-loan"): "理财与借贷是家庭金融的两面（增值与负债的风险）",
    ("fin-wealth", "digit-scam"): "高息理财与诈骗同源（收益诱惑是骗局入口）",
    ("city-property", "city-elevator"): "物业是小区日常治理，电梯改造是小区大事（同一社区权力场）",
    ("city-property", "gov-reg"): "物业纠纷需要监管（物业条例/业委会制度）",
    ("health-smoke", "public-civility"): "公共场所吸烟是公共边界问题的健康版",
    ("health-smoke", "medical-cost"): "吸烟/二手烟增加医疗负担（慢病源头）",
    ("digit-dating", "digit-scam"): "杀猪盘是电信诈骗的情感版（骗钱先骗心）",
    ("digit-dating", "relation-attach"): "网恋是依恋需求在数字时代的形态（更容易上头也更容易受伤）",
    # v15 新矛盾关联
    ("psy-single", "psy-lonely"): "独居是城市孤独的居住形态（一个人住+一个人扛）",
    ("psy-single", "fam-birth"): "独居推迟结婚生育（先独居后成家，婚育年龄后移）",
    ("edu-trainingloan", "fin-loan"): "培训贷是消费贷在教育场景的变体（贷款冲动消费）",
    ("edu-trainingloan", "edu-job"): "培训贷收割的是就业焦虑（想找工作→买培训→背贷款）",
    ("edu-gaokao", "edu-score"): "复读热是应试压力的极端化（一考定终身观念）",
    ("edu-gaokao", "study-kaoyan"): "复读与考研考公同源（对学历/稳定的执念）",
    ("fam-grandparenting", "fam-gener"): "隔代育儿是代际观念冲突的主战场（两代人带娃）",
    ("fam-grandparenting", "fam-parenting"): "老人参与育儿让育儿分工更复杂（三方协作者）",
    ("digit-phone", "digit-privacy"): "旧手机是隐私泄露的重灾区（数据不清理就卖）",
    ("digit-phone", "env-sort"): "旧手机回收是电子垃圾治理的一环（资源循环）",
    ("soc-tuango", "digit-live"): "社区团购是线上消费向菜篮子的延伸（平台买菜）",
    ("soc-tuango", "food-safe"): "团购生鲜的品质风险是食品安全的渠道版",
    ("traffic-trainfood", "tourism-trap"): "高铁餐饮与景区消费同属封闭场景价格（没得选）",
    ("traffic-trainfood", "gov-reg"): "高铁餐饮定价需要监管（垄断场景的价格治理）",
    ("edu-allowance", "edu-punish"): "零花钱教育是立规矩的财商版（规则+后果）",
    ("edu-allowance", "soc-consumer"): "从小教管钱是反消费主义的根基（会管钱才不被收割）",
    # v16 新矛盾关联
    ("edu-parttime", "edu-job"): "兼职是就业的提前演练（简历经验 vs 学业投入）",
    ("edu-parttime", "fin-loan"): "兼职赚钱是学生避免借贷的方式（自食其力 vs 消费贷）",
    ("fam-elderlove", "fam-remarry"): "父母再婚是重组家庭的老年版（子女接纳新成员）",
    ("fam-elderlove", "fam-gener"): "老人再婚是代际观念冲突的婚恋版（子女干涉 vs 老人自主）",
    ("pet-funeral", "pet-medical"): "宠物殡葬是养宠责任的终点（养得起也要送得好）",
    ("pet-funeral", "fam-solitude"): "宠物是孤独的解药，离世是孤独的回归（失去陪伴）",
    ("soc-reading", "digit-scroll"): "读书被短视频挤占是注意力争夺的一体两面",
    ("soc-reading", "edu-score"): "应试教育下的『课外阅读』被挤压（分数优先）",
    ("logistics-station", "gov-platform"): "驿站模式是平台用工的物流版（效率 vs 服务标准）",
    ("logistics-station", "soc-urban"): "城市化让上门难（高楼/门禁/人不在家）催生驿站",
    ("traffic-eldercar", "traffic-e"): "老年代步车是电动车治理的老年版（低速四轮）",
    ("traffic-eldercar", "age-digital"): "代步车与数字鸿沟同源——老人被现代系统排除",
    ("edu-hobby", "edu-chicken"): "兴趣班是鸡娃的才艺面（从补课到才艺的军备竞赛）",
    ("edu-hobby", "edu-allowance"): "兴趣班花钱与零花钱教育同属家庭财商课题",
    ("tourism-hotel", "tourism-trap"): "酒店卫生与景区宰客同属旅游消费的信任风险",
    ("tourism-hotel", "medical-cost"): "酒店卫生问题可致病——健康风险的住宿入口",
    # v17 新矛盾关联
    ("traffic-ridehailing", "gov-platform"): "网约车是平台用工的出行版（司机权益 vs 平台抽成）",
    ("traffic-ridehailing", "traffic-e"): "网约车与电动车同属出行新形态（安全监管课题）",
    ("fitness-card", "fin-loan"): "办卡预付费与消费贷同属『先付后用』的金融风险",
    ("fitness-card", "gov-reg"): "健身房跑路是预付卡监管缺位的典型案例",
    ("traffic-charge", "traffic-e"): "充电桩是电动车普及的基础设施瓶颈（买得起装不上）",
    ("traffic-charge", "city-property"): "装桩难本质是物业权责问题（公共区域管理）",
    ("city-library", "edu-score"): "占座高峰是考试季的物理表现（备考资源争夺）",
    ("city-library", "public-civility"): "占座是公共空间边界问题的学习版",
    ("health-height", "psy-appearance"): "身高焦虑是容貌/身材焦虑的儿童版（身体比较）",
    ("health-height", "health-weight"): "身高体重同属身体管理焦虑（数据焦虑）",
    ("pet-boarding", "city-pet"): "寄养是养宠责任的出行版（托付问题）",
    ("pet-boarding", "pet-medical"): "寄养风险（应激/交叉感染）是宠物健康问题",
    ("fam-giftmoney", "fam-wedding"): "随份子与婚庆消费同属人情经济（婚丧嫁娶的支出）",
    ("fam-giftmoney", "soc-consumer"): "份子钱通胀是消费主义的人情版（攀比升级）",
    ("culture-ticket", "digit-live"): "抢票是演出消费的线上版（平台/黄牛生态）",
    ("culture-ticket", "youth-idol"): "演唱会抢票是追星消费的高峰场景（为偶像付费）",
}

# 序列化为 JSON（供运行时加载）：conflicts 值改为 dict
out = {"conflicts": {k: {"name": v[0], "conflict": v[1], "q": v[2]}
                     for k, v in CONFLICT_META.items()},
       "links": [{"a": k[0], "b": k[1], "note": v} for k, v in LINK_NOTES.items()]}
with open(r"C:\Users\FuRongJun\AppData\Local\Programs\Python\Python310\lib\site-packages\wisdom\conflict_map.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=1)
print(f"矛盾关联映射: {len(CONFLICT_META)} 矛盾, {len(LINK_NOTES)} 条关联")
for k, v in list(LINK_NOTES.items())[:6]:
    print(f"  {k[0]} <-> {k[1]}: {v[:40]}")
